import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en' | 'es' | 'el' | 'ro' | 'pl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Navigation
    'nav.weekly': 'Weekly Entry',
    'nav.projects': 'Projects',
    'nav.export': 'Export',
    'nav.admin': 'Admin',
    'nav.reportBug': 'Report Bug',
    'nav.overview': 'Overview',
    'nav.welcome': 'Welkom',
    'nav.logout': 'Logout',
    
    // Project Management
    'project.addNew': 'Nieuw Project Toevoegen',
    'project.create': 'Maak een nieuw project voor urenregistratie',
    'project.name': 'Project Naam',
    'project.namePlaceholder': 'Voer project naam in',
    'project.client': 'Klant',
    'project.clientPlaceholder': 'Klant naam',
    'project.description': 'Beschrijving',
    'project.descriptionPlaceholder': 'Project beschrijving...',
    'project.createButton': 'Project Aanmaken',
    'project.active': 'Actieve Projecten',
    'project.manage': 'Beheer en volg je projecten',
    'project.viewDetails': 'Details Bekijken',
    'project.close': 'Sluiten',
    'project.reopen': 'Heropen',
    'project.delete': 'Verwijder',
    'project.deleteConfirm': 'Project Verwijderen',
    'project.deleteConfirmText': 'Weet je zeker dat je "{name}" wilt verwijderen? Alle gerelateerde timesheet entries worden ook verwijderd. Deze actie kan niet ongedaan worden gemaakt.',
    'project.cancel': 'Annuleren',
    'project.deleted': 'Project Verwijderd',
    'project.deletedText': '{name} is succesvol verwijderd. Alle gerelateerde timesheet entries zijn ook verwijderd.',
    'project.closed': 'Project Gesloten',
    'project.reopened': 'Project Heropend',
    'project.closedText': '{name} is gesloten. Er kunnen geen uren meer aan toegevoegd worden.',
    'project.reopenedText': '{name} is heropend. Er kunnen weer uren aan toegevoegd worden.',
    'project.status.active': 'Actief',
    'project.status.closed': 'Gesloten',
    'project.status.completed': 'Voltooid',
    'project.status.onHold': 'In Wacht',
    'project.hoursLogged': '{hours}h gelogd',
    'project.members': 'leden',
    'project.details': 'Project Details: {name}',
    'project.allEntries': 'Alle tijd entries voor dit project',
    'project.noEntries': 'Nog geen tijd entries.',
    
    // Weekly Entry
    'weekly.workType': 'Werk Type',
    'weekly.project': 'Project',
    'weekly.hours': 'Uren',
    'weekly.lunch': 'Lunch',
    'weekly.startTime': 'Start Tijd',
    'weekly.endTime': 'Eind Tijd',
    'weekly.submit': 'Verzenden',
    'weekly.submitAll': 'Verzend Alle Dagen',
    'weekly.submitDay': 'Verzend Dag',
    'weekly.add': 'Toevoegen',
    'weekly.confirmed': 'Deze week is bevestigd. Je kunt geen wijzigingen meer aanbrengen tot een admin dit heeft goedgekeurd of teruggezet.',
    
    // Export
    'export.title': 'Export Timesheet Data',
    'export.description': 'Export timesheet data naar Excel voor rapportage en analyse',
    'export.selectUser': 'Selecteer Gebruiker (optioneel)',
    'export.allUsers': 'Alle gebruikers',
    'export.selectUserHelp': 'Laat leeg om alle gebruikers te exporteren, of selecteer een specifieke gebruiker.',
    'export.allData': 'Export All Data',
    'export.dateRange': 'Export Datumbereik',
    'export.weekNumber': 'Export Week Nummer',
    'export.perUser': 'Export Per Gebruiker',
    'export.selectPeriod': 'Selecteer Periode',
    'export.selectDay': 'Selecteer Dag',
    'export.selectWeek': 'Selecteer Week (elke dag in de week)',
    'export.selectMonth': 'Selecteer Maand (elke dag in de maand)',
    'export.selectYear': 'Selecteer Jaar (elke dag in het jaar)',
    'export.exporting': 'Exporteren...',
    'export.day': 'Dag',
    'export.week': 'Week',
    'export.month': 'Maand',
    'export.year': 'Jaar',
    'export.note': 'Let op:',
    'export.adminNote': 'Admins kunnen alle data exporteren, een datumbereik selecteren, of per gebruiker exporteren. Selecteer een gebruiker om alleen die gebruiker te exporteren, of laat leeg voor alle gebruikers.',
    'export.userNote': 'Selecteer een periode en datum om je uren te exporteren naar Excel.',
    'export.weekPlaceholder': 'Week',
    'export.yearPlaceholder': 'Jaar',
    
    // Weekly Entry
    'weekly.viewMode.cards': 'Kaarten',
    'weekly.viewMode.overview': 'Overzicht',
    'weekly.daysOff': 'Vrije Dagen Over',
    'weekly.confirmWeek': 'Week Bevestigen',
    'weekly.confirmWeekText': 'Weet je zeker dat je deze week wilt bevestigen? Na bevestiging kun je als niet-admin geen wijzigingen meer aanbrengen.',
    'weekly.weekConfirmed': 'Week Bevestigd',
    'weekly.weekConfirmedText': 'Deze week is bevestigd en kan niet meer worden gewijzigd.',
    'weekly.type': 'Type',
    'weekly.projectPlaceholder': 'Project',
    'weekly.title': 'Weekly Calendar Entry',
    'weekly.week': 'Week',
    'weekly.prev': 'Prev',
    'weekly.next': 'Next',
    'weekly.exportWeek': 'Export Week to Excel',
    'weekly.daysOffRemaining': 'Days Off Remaining',
    'weekly.daysOffLeft': 'You have {days} days off left this year.',
    'weekly.weekOverview': 'Week Overview',
    'weekly.dayView': 'Day View',
    'weekly.entry': 'entry',
    'weekly.entries': 'entries',
    'weekly.day': 'Day',
    'weekly.van': 'From',
    'weekly.tot': 'To',
    'weekly.actions': 'Actions',
    'weekly.submittedEntries': 'Submitted Entries:',
    'weekly.addCustomProject': 'Add custom project',
    'weekly.clear': 'Clear',
    'weekly.startPlaceholder': 'Start (e.g. 08:10)',
    'weekly.endPlaceholder': 'End (e.g. 17:45)',
    'weekly.hoursPlaceholder': 'h',
    
    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.addUser': 'Gebruiker Toevoegen',
    'admin.email': 'Email',
    'admin.name': 'Naam',
    'admin.password': 'Wachtwoord',
    'admin.isAdmin': 'Admin',
    'admin.mustChangePassword': 'Moet wachtwoord wijzigen',
    'admin.createUser': 'Gebruiker Aanmaken',
    'admin.allUsers': 'Alle Gebruikers',
    'admin.pendingApproval': 'Wachtend op Goedkeuring',
    'admin.approve': 'Goedkeuren',
    'admin.reject': 'Afwijzen',
    'admin.resetPassword': 'Reset Wachtwoord',
    'admin.daysOff': 'Vrije Dagen',
    'admin.confirmedWeeks': 'Bevestigde Weken',
    'admin.approveWeek': 'Goedkeuren',
    'admin.reopenWeek': 'Heropen',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fout',
    'common.success': 'Succes',
    'common.cancel': 'Annuleren',
    'common.close': 'Sluiten',
    'common.save': 'Opslaan',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.confirm': 'Bevestigen',
  },
  en: {
    // Navigation
    'nav.weekly': 'Weekly Entry',
    'nav.projects': 'Projects',
    'nav.export': 'Export',
    'nav.admin': 'Admin',
    'nav.reportBug': 'Report Bug',
    'nav.overview': 'Overview',
    'nav.welcome': 'Welcome',
    'nav.logout': 'Logout',
    
    // Project Management
    'project.addNew': 'Add New Project',
    'project.create': 'Create a new project for time tracking',
    'project.name': 'Project Name',
    'project.namePlaceholder': 'Enter project name',
    'project.client': 'Client',
    'project.clientPlaceholder': 'Client name',
    'project.description': 'Description',
    'project.descriptionPlaceholder': 'Project description...',
    'project.createButton': 'Create Project',
    'project.active': 'Active Projects',
    'project.manage': 'Manage and track your projects',
    'project.viewDetails': 'View Details',
    'project.close': 'Close',
    'project.reopen': 'Reopen',
    'project.delete': 'Delete',
    'project.deleteConfirm': 'Delete Project',
    'project.deleteConfirmText': 'Are you sure you want to delete "{name}"? All related timesheet entries will also be deleted. This action cannot be undone.',
    'project.cancel': 'Cancel',
    'project.deleted': 'Project Deleted',
    'project.deletedText': '{name} has been successfully deleted. All related timesheet entries have also been deleted.',
    'project.closed': 'Project Closed',
    'project.reopened': 'Project Reopened',
    'project.closedText': '{name} has been closed. No more hours can be added to it.',
    'project.reopenedText': '{name} has been reopened. Hours can be added to it again.',
    'project.status.active': 'Active',
    'project.status.closed': 'Closed',
    'project.status.completed': 'Completed',
    'project.status.onHold': 'On Hold',
    'project.hoursLogged': '{hours}h logged',
    'project.members': 'members',
    'project.details': 'Project Details: {name}',
    'project.allEntries': 'All time entries for this project',
    'project.noEntries': 'No time entries yet.',
    
    // Weekly Entry
    'weekly.workType': 'Work Type',
    'weekly.project': 'Project',
    'weekly.hours': 'Hours',
    'weekly.lunch': 'Lunch',
    'weekly.startTime': 'Start Time',
    'weekly.endTime': 'End Time',
    'weekly.submit': 'Submit',
    'weekly.submitAll': 'Submit All Days',
    'weekly.submitDay': 'Submit Day',
    'weekly.add': 'Add',
    'weekly.confirmed': 'This week is confirmed. You cannot make any changes until an admin has approved or reset it.',
    
    // Export
    'export.title': 'Export Timesheet Data',
    'export.description': 'Export timesheet data to Excel for reporting and analysis',
    'export.selectUser': 'Select User (optional)',
    'export.allUsers': 'All users',
    'export.selectUserHelp': 'Leave empty to export all users, or select a specific user.',
    'export.allData': 'Export All Data',
    'export.dateRange': 'Export Date Range',
    'export.weekNumber': 'Export Week Number',
    'export.perUser': 'Export Per User',
    'export.selectPeriod': 'Select Period',
    'export.selectDay': 'Select Day',
    'export.selectWeek': 'Select Week (every day in the week)',
    'export.selectMonth': 'Select Month (every day in the month)',
    'export.selectYear': 'Select Year (every day in the year)',
    'export.exporting': 'Exporting...',
    'export.day': 'Day',
    'export.week': 'Week',
    'export.month': 'Month',
    'export.year': 'Year',
    'export.note': 'Note:',
    'export.adminNote': 'Admins can export all data, select a date range, or export per user. Select a user to export only that user, or leave empty for all users.',
    'export.userNote': 'Select a period and date to export your hours to Excel.',
    'export.weekPlaceholder': 'Week',
    'export.yearPlaceholder': 'Year',
    
    // Weekly Entry
    'weekly.viewMode.cards': 'Cards',
    'weekly.viewMode.overview': 'Overview',
    'weekly.daysOff': 'Days Off Remaining',
    'weekly.confirmWeek': 'Confirm Week',
    'weekly.confirmWeekText': 'Are you sure you want to confirm this week? After confirmation, you cannot make changes as a non-admin.',
    'weekly.weekConfirmed': 'Week Confirmed',
    'weekly.weekConfirmedText': 'This week is confirmed and cannot be changed anymore.',
    'weekly.type': 'Type',
    'weekly.projectPlaceholder': 'Project',
    'weekly.title': 'Weekly Calendar Entry',
    'weekly.week': 'Week',
    'weekly.prev': 'Prev',
    'weekly.next': 'Next',
    'weekly.exportWeek': 'Export Week to Excel',
    'weekly.daysOffRemaining': 'Days Off Remaining',
    'weekly.daysOffLeft': 'You have {days} days off left this year.',
    'weekly.weekOverview': 'Week Overview',
    'weekly.dayView': 'Day View',
    'weekly.entry': 'entry',
    'weekly.entries': 'entries',
    'weekly.day': 'Day',
    'weekly.van': 'From',
    'weekly.tot': 'To',
    'weekly.actions': 'Actions',
    'weekly.submittedEntries': 'Submitted Entries:',
    'weekly.addCustomProject': 'Add custom project',
    'weekly.clear': 'Clear',
    'weekly.startPlaceholder': 'Start (e.g. 08:10)',
    'weekly.endPlaceholder': 'End (e.g. 17:45)',
    'weekly.hoursPlaceholder': 'h',
    
    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.addUser': 'Add User',
    'admin.email': 'Email',
    'admin.name': 'Name',
    'admin.password': 'Password',
    'admin.isAdmin': 'Admin',
    'admin.mustChangePassword': 'Must change password',
    'admin.createUser': 'Create User',
    'admin.allUsers': 'All Users',
    'admin.pendingApproval': 'Pending Approval',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.resetPassword': 'Reset Password',
    'admin.daysOff': 'Days Off',
    'admin.confirmedWeeks': 'Confirmed Weeks',
    'admin.approveWeek': 'Approve',
    'admin.reopenWeek': 'Reopen',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.confirm': 'Confirm',
  },
  es: {
    // Navigation
    'nav.weekly': 'Entrada Semanal',
    'nav.projects': 'Proyectos',
    'nav.export': 'Exportar',
    'nav.admin': 'Administrador',
    'nav.reportBug': 'Reportar Error',
    'nav.overview': 'Resumen',
    'nav.welcome': 'Bienvenido',
    'nav.logout': 'Cerrar Sesión',
    
    // Project Management
    'project.addNew': 'Agregar Nuevo Proyecto',
    'project.create': 'Crear un nuevo proyecto para seguimiento de tiempo',
    'project.name': 'Nombre del Proyecto',
    'project.namePlaceholder': 'Ingrese el nombre del proyecto',
    'project.client': 'Cliente',
    'project.clientPlaceholder': 'Nombre del cliente',
    'project.description': 'Descripción',
    'project.descriptionPlaceholder': 'Descripción del proyecto...',
    'project.createButton': 'Crear Proyecto',
    'project.active': 'Proyectos Activos',
    'project.manage': 'Gestiona y rastrea tus proyectos',
    'project.viewDetails': 'Ver Detalles',
    'project.close': 'Cerrar',
    'project.reopen': 'Reabrir',
    'project.delete': 'Eliminar',
    'project.deleteConfirm': 'Eliminar Proyecto',
    'project.deleteConfirmText': '¿Estás seguro de que deseas eliminar "{name}"? Todas las entradas de timesheet relacionadas también se eliminarán. Esta acción no se puede deshacer.',
    'project.cancel': 'Cancelar',
    'project.deleted': 'Proyecto Eliminado',
    'project.deletedText': '{name} ha sido eliminado exitosamente. Todas las entradas de timesheet relacionadas también han sido eliminadas.',
    'project.closed': 'Proyecto Cerrado',
    'project.reopened': 'Proyecto Reabierto',
    'project.closedText': '{name} ha sido cerrado. No se pueden agregar más horas.',
    'project.reopenedText': '{name} ha sido reabierto. Se pueden agregar horas nuevamente.',
    'project.status.active': 'Activo',
    'project.status.closed': 'Cerrado',
    'project.status.completed': 'Completado',
    'project.status.onHold': 'En Espera',
    'project.hoursLogged': '{hours}h registradas',
    'project.members': 'miembros',
    'project.details': 'Detalles del Proyecto: {name}',
    'project.allEntries': 'Todas las entradas de tiempo para este proyecto',
    'project.noEntries': 'Aún no hay entradas de tiempo.',
    
    // Weekly Entry
    'weekly.workType': 'Tipo de Trabajo',
    'weekly.project': 'Proyecto',
    'weekly.hours': 'Horas',
    'weekly.lunch': 'Almuerzo',
    'weekly.startTime': 'Hora de Inicio',
    'weekly.endTime': 'Hora de Fin',
    'weekly.submit': 'Enviar',
    'weekly.submitAll': 'Enviar Todos los Días',
    'weekly.submitDay': 'Enviar Día',
    'weekly.add': 'Agregar',
    'weekly.confirmed': 'Esta semana está confirmada. No puedes hacer cambios hasta que un administrador la apruebe o la reinicie.',
    'weekly.viewMode.cards': 'Tarjetas',
    'weekly.viewMode.overview': 'Resumen',
    'weekly.daysOff': 'Días Libres Restantes',
    'weekly.confirmWeek': 'Confirmar Semana',
    'weekly.confirmWeekText': '¿Estás seguro de que deseas confirmar esta semana? Después de la confirmación, no podrás hacer cambios como no administrador.',
    'weekly.weekConfirmed': 'Semana Confirmada',
    'weekly.weekConfirmedText': 'Esta semana está confirmada y no se puede cambiar más.',
    'weekly.type': 'Tipo',
    'weekly.projectPlaceholder': 'Proyecto',
    
    // Export
    'export.title': 'Exportar Datos de Timesheet',
    'export.description': 'Exportar datos de timesheet a Excel para informes y análisis',
    'export.selectUser': 'Seleccionar Usuario (opcional)',
    'export.allUsers': 'Todos los usuarios',
    'export.selectUserHelp': 'Deje vacío para exportar todos los usuarios, o seleccione un usuario específico.',
    'export.allData': 'Exportar Todos los Datos',
    'export.dateRange': 'Exportar Rango de Fechas',
    'export.weekNumber': 'Exportar Número de Semana',
    'export.perUser': 'Exportar Por Usuario',
    'export.selectPeriod': 'Seleccionar Período',
    'export.selectDay': 'Seleccionar Día',
    'export.selectWeek': 'Seleccionar Semana (cada día de la semana)',
    'export.selectMonth': 'Seleccionar Mes (cada día del mes)',
    'export.selectYear': 'Seleccionar Año (cada día del año)',
    'export.exporting': 'Exportando...',
    'export.day': 'Día',
    'export.week': 'Semana',
    'export.month': 'Mes',
    'export.year': 'Año',
    'export.note': 'Nota:',
    'export.adminNote': 'Los administradores pueden exportar todos los datos, seleccionar un rango de fechas o exportar por usuario. Seleccione un usuario para exportar solo ese usuario, o deje vacío para todos los usuarios.',
    'export.userNote': 'Seleccione un período y fecha para exportar sus horas a Excel.',
    'export.weekPlaceholder': 'Semana',
    'export.yearPlaceholder': 'Año',
    
    // Admin Panel
    'admin.title': 'Panel de Administración',
    'admin.addUser': 'Agregar Usuario',
    'admin.email': 'Correo Electrónico',
    'admin.name': 'Nombre',
    'admin.password': 'Contraseña',
    'admin.isAdmin': 'Administrador',
    'admin.mustChangePassword': 'Debe cambiar contraseña',
    'admin.createUser': 'Crear Usuario',
    'admin.allUsers': 'Todos los Usuarios',
    'admin.pendingApproval': 'Pendiente de Aprobación',
    'admin.approve': 'Aprobar',
    'admin.reject': 'Rechazar',
    'admin.resetPassword': 'Restablecer Contraseña',
    'admin.daysOff': 'Días Libres',
    'admin.confirmedWeeks': 'Semanas Confirmadas',
    'admin.approveWeek': 'Aprobar',
    'admin.reopenWeek': 'Reabrir',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.close': 'Cerrar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.confirm': 'Confirmar',
  },
  el: {
    // Navigation
    'nav.weekly': 'Εβδομαδιαία Καταχώρηση',
    'nav.projects': 'Έργα',
    'nav.export': 'Εξαγωγή',
    'nav.admin': 'Διαχειριστής',
    'nav.reportBug': 'Αναφορά Σφάλματος',
    'nav.overview': 'Επισκόπηση',
    'nav.welcome': 'Καλώς ήρθατε',
    'nav.logout': 'Αποσύνδεση',
    
    // Project Management
    'project.addNew': 'Προσθήκη Νέου Έργου',
    'project.create': 'Δημιουργία νέου έργου για παρακολούθηση χρόνου',
    'project.name': 'Όνομα Έργου',
    'project.namePlaceholder': 'Εισάγετε όνομα έργου',
    'project.client': 'Πελάτης',
    'project.clientPlaceholder': 'Όνομα πελάτη',
    'project.description': 'Περιγραφή',
    'project.descriptionPlaceholder': 'Περιγραφή έργου...',
    'project.createButton': 'Δημιουργία Έργου',
    'project.active': 'Ενεργά Έργα',
    'project.manage': 'Διαχείριση και παρακολούθηση των έργων σας',
    'project.viewDetails': 'Προβολή Λεπτομερειών',
    'project.close': 'Κλείσιμο',
    'project.reopen': 'Επαναφορά',
    'project.delete': 'Διαγραφή',
    'project.deleteConfirm': 'Διαγραφή Έργου',
    'project.deleteConfirmText': 'Είστε βέβαιοι ότι θέλετε να διαγράψετε το "{name}"; Όλες οι σχετικές καταχωρήσεις timesheet θα διαγραφούν επίσης. Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
    'project.cancel': 'Ακύρωση',
    'project.deleted': 'Έργο Διαγράφηκε',
    'project.deletedText': 'Το {name} διαγράφηκε με επιτυχία. Όλες οι σχετικές καταχωρήσεις timesheet διαγράφηκαν επίσης.',
    'project.closed': 'Έργο Κλείστηκε',
    'project.reopened': 'Έργο Επαναφέρθηκε',
    'project.closedText': 'Το {name} έκλεισε. Δεν μπορούν να προστεθούν περισσότερες ώρες.',
    'project.reopenedText': 'Το {name} επαναφέρθηκε. Μπορούν να προστεθούν ώρες ξανά.',
    'project.status.active': 'Ενεργό',
    'project.status.closed': 'Κλειστό',
    'project.status.completed': 'Ολοκληρωμένο',
    'project.status.onHold': 'Σε Αναμονή',
    'project.hoursLogged': '{hours}ω καταγράφηκαν',
    'project.members': 'μέλη',
    'project.details': 'Λεπτομέρειες Έργου: {name}',
    'project.allEntries': 'Όλες οι καταχωρήσεις χρόνου για αυτό το έργο',
    'project.noEntries': 'Δεν υπάρχουν ακόμα καταχωρήσεις χρόνου.',
    
    // Weekly Entry
    'weekly.workType': 'Τύπος Εργασίας',
    'weekly.project': 'Έργο',
    'weekly.hours': 'Ώρες',
    'weekly.lunch': 'Γεύμα',
    'weekly.startTime': 'Ώρα Έναρξης',
    'weekly.endTime': 'Ώρα Λήξης',
    'weekly.submit': 'Υποβολή',
    'weekly.submitAll': 'Υποβολή Όλων των Ημερών',
    'weekly.submitDay': 'Υποβολή Ημέρας',
    'weekly.add': 'Προσθήκη',
    'weekly.confirmed': 'Αυτή η εβδομάδα έχει επιβεβαιωθεί. Δεν μπορείτε να κάνετε αλλαγές μέχρι ένας διαχειριστής να την εγκρίνει ή να την επαναφέρει.',
    'weekly.viewMode.cards': 'Κάρτες',
    'weekly.viewMode.overview': 'Επισκόπηση',
    'weekly.daysOff': 'Υπόλοιπες Ημέρες Άδειας',
    'weekly.confirmWeek': 'Επιβεβαίωση Εβδομάδας',
    'weekly.type': 'Τύπος',
    'weekly.projectPlaceholder': 'Έργο',
    'weekly.confirmWeekText': 'Είστε βέβαιοι ότι θέλετε να επιβεβαιώσετε αυτή την εβδομάδα; Μετά την επιβεβαίωση, δεν θα μπορείτε να κάνετε αλλαγές ως μη διαχειριστής.',
    'weekly.weekConfirmed': 'Εβδομάδα Επιβεβαιώθηκε',
    'weekly.weekConfirmedText': 'Αυτή η εβδομάδα έχει επιβεβαιωθεί και δεν μπορεί να αλλάξει πλέον.',
    'weekly.title': 'Εβδομαδιαία Καταχώρηση Ημερολογίου',
    'weekly.week': 'Εβδομάδα',
    'weekly.prev': 'Προηγούμενη',
    'weekly.next': 'Επόμενη',
    'weekly.exportWeek': 'Εξαγωγή Εβδομάδας σε Excel',
    'weekly.daysOffRemaining': 'Υπόλοιπες Ημέρες Άδειας',
    'weekly.daysOffLeft': 'Έχετε {days} ημέρες άδειας αριστερά φέτος.',
    'weekly.weekOverview': 'Επισκόπηση Εβδομάδας',
    'weekly.dayView': 'Προβολή Ημέρας',
    'weekly.entry': 'καταχώρηση',
    'weekly.entries': 'καταχωρήσεις',
    'weekly.day': 'Ημέρα',
    'weekly.van': 'Από',
    'weekly.tot': 'Έως',
    'weekly.actions': 'Ενέργειες',
    'weekly.submittedEntries': 'Υποβληθείσες Καταχωρήσεις:',
    'weekly.addCustomProject': 'Προσθήκη προσαρμοσμένου έργου',
    'weekly.clear': 'Εκκαθάριση',
    'weekly.startPlaceholder': 'Έναρξη (π.χ. 08:10)',
    'weekly.endPlaceholder': 'Λήξη (π.χ. 17:45)',
    'weekly.hoursPlaceholder': 'ω',
    
    // Export
    'export.title': 'Εξαγωγή Δεδομένων Timesheet',
    'export.description': 'Εξαγωγή δεδομένων timesheet σε Excel για αναφορές και ανάλυση',
    'export.selectUser': 'Επιλογή Χρήστη (προαιρετικό)',
    'export.allUsers': 'Όλοι οι χρήστες',
    'export.selectUserHelp': 'Αφήστε κενό για εξαγωγή όλων των χρηστών ή επιλέξτε συγκεκριμένο χρήστη.',
    'export.allData': 'Εξαγωγή Όλων των Δεδομένων',
    'export.dateRange': 'Εξαγωγή Εύρους Ημερομηνιών',
    'export.weekNumber': 'Εξαγωγή Αριθμού Εβδομάδας',
    'export.perUser': 'Εξαγωγή Ανά Χρήστη',
    'export.selectPeriod': 'Επιλογή Περιόδου',
    'export.selectDay': 'Επιλογή Ημέρας',
    'export.selectWeek': 'Επιλογή Εβδομάδας (κάθε ημέρα της εβδομάδας)',
    'export.selectMonth': 'Επιλογή Μήνα (κάθε ημέρα του μήνα)',
    'export.selectYear': 'Επιλογή Έτους (κάθε ημέρα του έτους)',
    'export.exporting': 'Εξαγωγή...',
    'export.day': 'Ημέρα',
    'export.week': 'Εβδομάδα',
    'export.month': 'Μήνας',
    'export.year': 'Έτος',
    'export.note': 'Σημείωση:',
    'export.adminNote': 'Οι διαχειριστές μπορούν να εξάγουν όλα τα δεδομένα, να επιλέξουν εύρος ημερομηνιών ή να εξάγουν ανά χρήστη. Επιλέξτε χρήστη για εξαγωγή μόνο αυτού του χρήστη ή αφήστε κενό για όλους τους χρήστες.',
    'export.userNote': 'Επιλέξτε περίοδο και ημερομηνία για εξαγωγή των ωρών σας σε Excel.',
    'export.weekPlaceholder': 'Εβδομάδα',
    'export.yearPlaceholder': 'Έτος',
    
    // Admin Panel
    'admin.title': 'Πίνακας Διαχείρισης',
    'admin.addUser': 'Προσθήκη Χρήστη',
    'admin.email': 'Email',
    'admin.name': 'Όνομα',
    'admin.password': 'Κωδικός',
    'admin.isAdmin': 'Διαχειριστής',
    'admin.mustChangePassword': 'Πρέπει να αλλάξει κωδικό',
    'admin.createUser': 'Δημιουργία Χρήστη',
    'admin.allUsers': 'Όλοι οι Χρήστες',
    'admin.pendingApproval': 'Εκκρεμεί Έγκριση',
    'admin.approve': 'Έγκριση',
    'admin.reject': 'Απόρριψη',
    'admin.resetPassword': 'Επαναφορά Κωδικού',
    'admin.daysOff': 'Ημέρες Άδειας',
    'admin.confirmedWeeks': 'Επιβεβαιωμένες Εβδομάδες',
    'admin.approveWeek': 'Έγκριση',
    'admin.reopenWeek': 'Επαναφορά',
    
    // Common
    'common.loading': 'Φόρτωση...',
    'common.error': 'Σφάλμα',
    'common.success': 'Επιτυχία',
    'common.cancel': 'Ακύρωση',
    'common.close': 'Κλείσιμο',
    'common.save': 'Αποθήκευση',
    'common.delete': 'Διαγραφή',
    'common.edit': 'Επεξεργασία',
    'common.confirm': 'Επιβεβαίωση',
  },
  ro: {
    // Navigation
    'nav.weekly': 'Intrare Săptămânală',
    'nav.projects': 'Proiecte',
    'nav.export': 'Export',
    'nav.admin': 'Administrator',
    'nav.reportBug': 'Raportează Eroare',
    'nav.overview': 'Prezentare Generală',
    'nav.welcome': 'Bun venit',
    'nav.logout': 'Deconectare',
    
    // Project Management
    'project.addNew': 'Adaugă Proiect Nou',
    'project.create': 'Creează un proiect nou pentru urmărirea timpului',
    'project.name': 'Nume Proiect',
    'project.namePlaceholder': 'Introduceți numele proiectului',
    'project.client': 'Client',
    'project.clientPlaceholder': 'Nume client',
    'project.description': 'Descriere',
    'project.descriptionPlaceholder': 'Descriere proiect...',
    'project.createButton': 'Creează Proiect',
    'project.active': 'Proiecte Active',
    'project.manage': 'Gestionează și urmărește proiectele tale',
    'project.viewDetails': 'Vezi Detalii',
    'project.close': 'Închide',
    'project.reopen': 'Redeschide',
    'project.delete': 'Șterge',
    'project.deleteConfirm': 'Șterge Proiect',
    'project.deleteConfirmText': 'Ești sigur că vrei să ștergi "{name}"; Toate intrările de timesheet asociate vor fi de asemenea șterse. Această acțiune nu poate fi anulată.',
    'project.cancel': 'Anulează',
    'project.deleted': 'Proiect Șters',
    'project.deletedText': '{name} a fost șters cu succes. Toate intrările de timesheet asociate au fost de asemenea șterse.',
    'project.closed': 'Proiect Închis',
    'project.reopened': 'Proiect Redeschis',
    'project.closedText': '{name} a fost închis. Nu se mai pot adăuga ore.',
    'project.reopenedText': '{name} a fost redeschis. Se pot adăuga ore din nou.',
    'project.status.active': 'Activ',
    'project.status.closed': 'Închis',
    'project.status.completed': 'Finalizat',
    'project.status.onHold': 'În Așteptare',
    'project.hoursLogged': '{hours}h înregistrate',
    'project.members': 'membri',
    'project.details': 'Detalii Proiect: {name}',
    'project.allEntries': 'Toate intrările de timp pentru acest proiect',
    'project.noEntries': 'Nu există încă intrări de timp.',
    
    // Weekly Entry
    'weekly.workType': 'Tip Muncă',
    'weekly.project': 'Proiect',
    'weekly.hours': 'Ore',
    'weekly.lunch': 'Prânz',
    'weekly.startTime': 'Ora Început',
    'weekly.endTime': 'Ora Sfârșit',
    'weekly.submit': 'Trimite',
    'weekly.submitAll': 'Trimite Toate Zilele',
    'weekly.submitDay': 'Trimite Ziua',
    'weekly.add': 'Adaugă',
    'weekly.confirmed': 'Această săptămână este confirmată. Nu poți face modificări până când un administrator o aprobă sau o resetează.',
    'weekly.viewMode.cards': 'Carduri',
    'weekly.viewMode.overview': 'Prezentare Generală',
    'weekly.daysOff': 'Zile Libere Rămase',
    'weekly.confirmWeek': 'Confirmă Săptămâna',
    'weekly.confirmWeekText': 'Ești sigur că vrei să confirmi această săptămână? După confirmare, nu vei mai putea face modificări ca non-administrator.',
    'weekly.weekConfirmed': 'Săptămână Confirmată',
    'weekly.weekConfirmedText': 'Această săptămână este confirmată și nu mai poate fi modificată.',
    'weekly.type': 'Tip',
    'weekly.projectPlaceholder': 'Proiect',
    
    // Export
    'export.title': 'Export Date Timesheet',
    'export.description': 'Export date timesheet în Excel pentru raportare și analiză',
    'export.selectUser': 'Selectează Utilizator (opțional)',
    'export.allUsers': 'Toți utilizatorii',
    'export.selectUserHelp': 'Lăsați gol pentru a exporta toți utilizatorii sau selectați un utilizator specific.',
    'export.allData': 'Export Toate Datele',
    'export.dateRange': 'Export Interval Date',
    'export.weekNumber': 'Export Număr Săptămână',
    'export.perUser': 'Export Pe Utilizator',
    'export.selectPeriod': 'Selectează Perioadă',
    'export.selectDay': 'Selectează Ziua',
    'export.selectWeek': 'Selectează Săptămâna (fiecare zi din săptămână)',
    'export.selectMonth': 'Selectează Luna (fiecare zi din lună)',
    'export.selectYear': 'Selectează Anul (fiecare zi din an)',
    'export.exporting': 'Exportare...',
    'export.day': 'Zi',
    'export.week': 'Săptămână',
    'export.month': 'Lună',
    'export.year': 'An',
    'export.note': 'Notă:',
    'export.adminNote': 'Administratorii pot exporta toate datele, selecta un interval de date sau exporta pe utilizator. Selectați un utilizator pentru a exporta doar acel utilizator sau lăsați gol pentru toți utilizatorii.',
    'export.userNote': 'Selectați o perioadă și dată pentru a vă exporta orele în Excel.',
    'export.weekPlaceholder': 'Săptămână',
    'export.yearPlaceholder': 'An',
    
    // Admin Panel
    'admin.title': 'Panou Administrator',
    'admin.addUser': 'Adaugă Utilizator',
    'admin.email': 'Email',
    'admin.name': 'Nume',
    'admin.password': 'Parolă',
    'admin.isAdmin': 'Administrator',
    'admin.mustChangePassword': 'Trebuie să schimbe parola',
    'admin.createUser': 'Creează Utilizator',
    'admin.allUsers': 'Toți Utilizatorii',
    'admin.pendingApproval': 'În Așteptarea Aprobării',
    'admin.approve': 'Aprobă',
    'admin.reject': 'Respinge',
    'admin.resetPassword': 'Resetează Parola',
    'admin.daysOff': 'Zile Libere',
    'admin.confirmedWeeks': 'Săptămâni Confirmate',
    'admin.approveWeek': 'Aprobă',
    'admin.reopenWeek': 'Redeschide',
    
    // Common
    'common.loading': 'Se încarcă...',
    'common.error': 'Eroare',
    'common.success': 'Succes',
    'common.cancel': 'Anulează',
    'common.close': 'Închide',
    'common.save': 'Salvează',
    'common.delete': 'Șterge',
    'common.edit': 'Editează',
    'common.confirm': 'Confirmă',
  },
  pl: {
    // Navigation
    'nav.weekly': 'Wpis Tygodniowy',
    'nav.projects': 'Projekty',
    'nav.export': 'Eksport',
    'nav.admin': 'Administrator',
    'nav.reportBug': 'Zgłoś Błąd',
    'nav.overview': 'Przegląd',
    'nav.welcome': 'Witamy',
    'nav.logout': 'Wyloguj',
    
    // Project Management
    'project.addNew': 'Dodaj Nowy Projekt',
    'project.create': 'Utwórz nowy projekt do śledzenia czasu',
    'project.name': 'Nazwa Projektu',
    'project.namePlaceholder': 'Wprowadź nazwę projektu',
    'project.client': 'Klient',
    'project.clientPlaceholder': 'Nazwa klienta',
    'project.description': 'Opis',
    'project.descriptionPlaceholder': 'Opis projektu...',
    'project.createButton': 'Utwórz Projekt',
    'project.active': 'Aktywne Projekty',
    'project.manage': 'Zarządzaj i śledź swoje projekty',
    'project.viewDetails': 'Zobacz Szczegóły',
    'project.close': 'Zamknij',
    'project.reopen': 'Otwórz Ponownie',
    'project.delete': 'Usuń',
    'project.deleteConfirm': 'Usuń Projekt',
    'project.deleteConfirmText': 'Czy na pewno chcesz usunąć "{name}"; Wszystkie powiązane wpisy timesheet również zostaną usunięte. Tej akcji nie można cofnąć.',
    'project.cancel': 'Anuluj',
    'project.deleted': 'Projekt Usunięty',
    'project.deletedText': '{name} został pomyślnie usunięty. Wszystkie powiązane wpisy timesheet również zostały usunięte.',
    'project.closed': 'Projekt Zamknięty',
    'project.reopened': 'Projekt Otworzony Ponownie',
    'project.closedText': '{name} został zamknięty. Nie można już dodawać godzin.',
    'project.reopenedText': '{name} został otwarty ponownie. Można ponownie dodawać godziny.',
    'project.status.active': 'Aktywny',
    'project.status.closed': 'Zamknięty',
    'project.status.completed': 'Ukończony',
    'project.status.onHold': 'Wstrzymany',
    'project.hoursLogged': '{hours}h zarejestrowano',
    'project.members': 'członkowie',
    'project.details': 'Szczegóły Projektu: {name}',
    'project.allEntries': 'Wszystkie wpisy czasu dla tego projektu',
    'project.noEntries': 'Brak jeszcze wpisów czasu.',
    
    // Weekly Entry
    'weekly.workType': 'Typ Pracy',
    'weekly.project': 'Projekt',
    'weekly.hours': 'Godziny',
    'weekly.lunch': 'Obiad',
    'weekly.startTime': 'Godzina Rozpoczęcia',
    'weekly.endTime': 'Godzina Zakończenia',
    'weekly.submit': 'Wyślij',
    'weekly.submitAll': 'Wyślij Wszystkie Dni',
    'weekly.submitDay': 'Wyślij Dzień',
    'weekly.add': 'Dodaj',
    'weekly.confirmed': 'Ten tydzień jest potwierdzony. Nie możesz wprowadzać zmian, dopóki administrator nie zatwierdzi lub nie zresetuje go.',
    'weekly.viewMode.cards': 'Karty',
    'weekly.viewMode.overview': 'Przegląd',
    'weekly.daysOff': 'Pozostałe Dni Wolne',
    'weekly.confirmWeek': 'Potwierdź Tydzień',
    'weekly.confirmWeekText': 'Czy na pewno chcesz potwierdzić ten tydzień? Po potwierdzeniu nie będziesz mógł wprowadzać zmian jako nie-administrator.',
    'weekly.weekConfirmed': 'Tydzień Potwierdzony',
    'weekly.weekConfirmedText': 'Ten tydzień jest potwierdzony i nie może być już zmieniony.',
    'weekly.type': 'Typ',
    'weekly.projectPlaceholder': 'Projekt',
    
    // Export
    'export.title': 'Eksport Danych Timesheet',
    'export.description': 'Eksport danych timesheet do Excel do raportowania i analizy',
    'export.selectUser': 'Wybierz Użytkownika (opcjonalnie)',
    'export.allUsers': 'Wszyscy użytkownicy',
    'export.selectUserHelp': 'Pozostaw puste, aby wyeksportować wszystkich użytkowników lub wybierz konkretnego użytkownika.',
    'export.allData': 'Eksport Wszystkich Danych',
    'export.dateRange': 'Eksport Zakresu Dat',
    'export.weekNumber': 'Eksport Numeru Tygodnia',
    'export.perUser': 'Eksport Na Użytkownika',
    'export.selectPeriod': 'Wybierz Okres',
    'export.selectDay': 'Wybierz Dzień',
    'export.selectWeek': 'Wybierz Tydzień (każdy dzień tygodnia)',
    'export.selectMonth': 'Wybierz Miesiąc (każdy dzień miesiąca)',
    'export.selectYear': 'Wybierz Rok (każdy dzień roku)',
    'export.exporting': 'Eksportowanie...',
    'export.day': 'Dzień',
    'export.week': 'Tydzień',
    'export.month': 'Miesiąc',
    'export.year': 'Rok',
    'export.note': 'Uwaga:',
    'export.adminNote': 'Administratorzy mogą eksportować wszystkie dane, wybrać zakres dat lub eksportować na użytkownika. Wybierz użytkownika, aby wyeksportować tylko tego użytkownika, lub pozostaw puste dla wszystkich użytkowników.',
    'export.userNote': 'Wybierz okres i datę, aby wyeksportować swoje godziny do Excel.',
    'export.weekPlaceholder': 'Tydzień',
    'export.yearPlaceholder': 'Rok',
    
    // Admin Panel
    'admin.title': 'Panel Administratora',
    'admin.addUser': 'Dodaj Użytkownika',
    'admin.email': 'Email',
    'admin.name': 'Imię',
    'admin.password': 'Hasło',
    'admin.isAdmin': 'Administrator',
    'admin.mustChangePassword': 'Musi zmienić hasło',
    'admin.createUser': 'Utwórz Użytkownika',
    'admin.allUsers': 'Wszyscy Użytkownicy',
    'admin.pendingApproval': 'Oczekuje Na Zatwierdzenie',
    'admin.approve': 'Zatwierdź',
    'admin.reject': 'Odrzuć',
    'admin.resetPassword': 'Resetuj Hasło',
    'admin.daysOff': 'Dni Wolne',
    'admin.confirmedWeeks': 'Potwierdzone Tygodnie',
    'admin.approveWeek': 'Zatwierdź',
    'admin.reopenWeek': 'Otwórz Ponownie',
    
    // Common
    'common.loading': 'Ładowanie...',
    'common.error': 'Błąd',
    'common.success': 'Sukces',
    'common.cancel': 'Anuluj',
    'common.close': 'Zamknij',
    'common.save': 'Zapisz',
    'common.delete': 'Usuń',
    'common.edit': 'Edytuj',
    'common.confirm': 'Potwierdź',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Get language from localStorage or default to English
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('bampro_language');
      if (saved && (saved === 'nl' || saved === 'en')) {
        return saved as Language;
      }
    }
    return 'en';
  });

  // Save language preference to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('bampro_language', lang);
    }
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || translations['en'][key] || key;
    
    // Replace parameters like {name} with actual values
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, String(params[param]));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

