import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Navigation
    'nav.weekly': 'Wekelijkse Invoer',
    'nav.viewHours': 'Ingevulde Uren',
    'nav.projects': 'Projecten',
    'nav.export': 'Exporteren',
    'nav.admin': 'Beheer',
    'nav.weeks': 'Weken',
    'nav.reportBug': 'Rapporteer Bug',
    'nav.overview': 'Overzicht',
    'nav.welcome': 'Welkom',
    'nav.logout': 'Uitloggen',
    'nav.clickToViewProfile': 'Klik om je profiel te bekijken en te bewerken',
    
    // Project Management
    'project.addNew': 'Nieuw Project Toevoegen',
    'project.create': 'Maak een nieuw project voor urenregistratie',
    'project.name': 'Project Naam',
    'project.namePlaceholder': 'Voer project naam in',
    'project.client': 'Klant',
    'project.clientPlaceholder': 'Klant naam',
    'project.description': 'Beschrijving',
    'project.descriptionPlaceholder': 'Project beschrijving...',
    'project.createButton': 'Project Aanmaken',
    'project.active': 'Actieve Projecten',
    'project.manage': 'Beheer en volg je projecten',
    'project.viewDetails': 'Details Bekijken',
    'project.close': 'Sluiten',
    'project.reopen': 'Heropen',
    'project.delete': 'Verwijder',
    'project.deleteConfirm': 'Project Verwijderen',
    'project.deleteConfirmText': 'Weet je zeker dat je "{name}" wilt verwijderen? Alle gerelateerde timesheet entries worden ook verwijderd. Deze actie kan niet ongedaan worden gemaakt.',
    'project.cancel': 'Annuleren',
    'project.deleted': 'Project Verwijderd',
    'project.deletedText': '{name} is succesvol verwijderd. Alle gerelateerde timesheet entries zijn ook verwijderd.',
    'project.closed': 'Project Gesloten',
    'project.reopened': 'Project Heropend',
    'project.closedText': '{name} is gesloten. Er kunnen geen uren meer aan toegevoegd worden.',
    'project.reopenedText': '{name} is heropend. Er kunnen weer uren aan toegevoegd worden.',
    'project.status.active': 'Actief',
    'project.status.closed': 'Gesloten',
    'project.status.completed': 'Voltooid',
    'project.status.onHold': 'In Wacht',
    'project.hoursLogged': '{hours}h gelogd',
    'project.members': 'leden',
    'project.details': 'Project Details: {name}',
    'project.allEntries': 'Alle tijd entries voor dit project',
    'project.noEntries': 'Nog geen tijd entries.',
    
    // Weekly Entry
    'weekly.workType': 'Werk Type',
    'weekly.project': 'Project',
    'weekly.hours': 'Uren',
    'weekly.lunch': 'Lunch',
    'weekly.startTime': 'Start Tijd',
    'weekly.endTime': 'Eind Tijd',
    'weekly.submit': 'Verzenden',
    'weekly.submitAll': 'Verzend Alle Dagen',
    'weekly.submitDay': 'Verzend Dag',
    'weekly.add': 'Toevoegen',
    'weekly.confirmed': 'Deze week is bevestigd. Je kunt geen wijzigingen meer aanbrengen tot een admin dit heeft goedgekeurd of teruggezet.',
    
    // Export
    'export.title': 'Export Timesheet Data',
    'export.description': 'Export timesheet data naar Excel voor rapportage en analyse',
    'export.selectUser': 'Selecteer Gebruiker (optioneel)',
    'export.allUsers': 'Alle gebruikers',
    'export.selectUserHelp': 'Laat leeg om alle gebruikers te exporteren, of selecteer een specifieke gebruiker.',
    'export.allData': 'Export All Data',
    'export.dateRange': 'Export Datumbereik',
    'export.weekNumber': 'Export Week Nummer',
    'export.perUser': 'Export Per Gebruiker',
    'export.selectPeriod': 'Selecteer Periode',
    'export.selectDay': 'Selecteer Dag',
    'export.selectWeek': 'Selecteer Week (elke dag in de week)',
    'export.selectMonth': 'Selecteer Maand (elke dag in de maand)',
    'export.selectYear': 'Selecteer Jaar (elke dag in het jaar)',
    'export.exporting': 'Exporteren...',
    'export.day': 'Dag',
    'export.week': 'Week',
    'export.month': 'Maand',
    'export.year': 'Jaar',
    'export.note': 'Let op:',
    'export.adminNote': 'Admins kunnen alle data exporteren, een datumbereik selecteren, of per gebruiker exporteren. Selecteer een gebruiker om alleen die gebruiker te exporteren, of laat leeg voor alle gebruikers.',
    'export.userNote': 'Selecteer een periode en datum om je uren te exporteren naar Excel.',
    'export.weekPlaceholder': 'Week',
    'export.yearPlaceholder': 'Jaar',
    'export.overtimeSummary': 'Overuren Samenvatting',
    'export.overtimeTotal': 'Totaal overuren',
    'export.overtime125': 'Overuren 125%',
    'export.overtime150': 'Overuren 150%',
    'export.overtime200': 'Overuren 200%',
    'export.overnightStays': 'Overnachtingen',
    'export.overnightDates': 'Data overnachtingen',
    
    // Weekly Entry
    'weekly.viewMode.cards': 'Kaarten',
    'weekly.viewMode.overview': 'Overzicht',
    'weekly.daysOff': 'Vrije Dagen Over',
    'weekly.confirmWeek': 'Week Bevestigen',
    'weekly.confirmWeekText': 'Weet je zeker dat je deze week wilt bevestigen? Na bevestiging kun je geen wijzigingen meer aanbrengen.',
    'weekly.weekConfirmed': 'Week Bevestigd',
    'weekly.weekConfirmedText': 'Deze week is bevestigd en kan niet meer worden gewijzigd.',
    'weekly.weekConfirmedSendEmailPrompt': 'Je week is bevestigd en vergrendeld. Wil je het Excel-bestand naar administratie versturen?',
    'weekly.skip': 'Overslaan',
    'weekly.type': 'Type',
    'weekly.projectPlaceholder': 'Project',
    'weekly.title': 'Wekelijkse Kalender Invoer',
    'weekly.week': 'Week',
    'weekly.prev': 'Vorige',
    'weekly.next': 'Volgende',
    'weekly.selectWeek': 'Selecteer Week',
    'weekly.exportWeek': 'Exporteer Week naar Excel',
    'weekly.daysOffRemaining': 'Vrije Dagen Over',
    'weekly.daysOffLeft': 'Je hebt nog {days} vrije dagen dit jaar.',
    'weekly.weekOverview': 'Week Overzicht',
    'weekly.dayView': 'Dag Weergave',
    'weekly.entry': 'invoer',
    'weekly.entries': 'invoeren',
    'weekly.day': 'Dag',
    'weekly.van': 'Van',
    'weekly.tot': 'Tot',
    'weekly.from': 'Van',
    'weekly.to': 'Tot',
    'weekly.actions': 'Acties',
    'weekly.submittedEntries': 'Ingediende Invoeren:',
    'weekly.addCustomProject': 'Voeg aangepast project toe',
    'weekly.clear': 'Wissen',
    'weekly.startPlaceholder': 'Start (bijv. 08:10)',
    'weekly.endPlaceholder': 'Eind (bijv. 17:45)',
    'weekly.hoursPlaceholder': 'u',
    'weekly.copyPrevious': 'Kopieer Vorige',
    'weekly.searchWorkType': 'Zoek werk type...',
    'weekly.noWorkTypeFound': 'Geen werk type gevonden.',
    'weekly.switchToOriginalView': 'Schakel naar originele weergave',
    'weekly.addEntry': 'Voeg Invoer Toe',
    'weekly.selectWorkType': 'Selecteer werk type...',
    'weekly.selectProject': 'Selecteer project...',
    'weekly.searchProject': 'Zoek project of typ om nieuw aan te maken...',
    'weekly.noProjectFound': 'Geen project gevonden. Druk op Enter om aan te maken',
    'weekly.noProjectsFound': 'Geen projecten gevonden.',
    'weekly.create': 'Maak',
    'weekly.time': 'Tijd',
    'weekly.save': 'Opslaan',
    'weekly.editEntry': 'Bewerk invoer',
    'weekly.deleteEntry': 'Verwijder invoer',
    'weekly.fullDayOff': 'Hele dag vrij (8 uren)',
    'weekly.overnightStay': 'Overnachting (niet thuis geslapen)',
    'weekly.weekConfirmedWarning': 'Deze week is bevestigd. Je kunt geen wijzigingen meer aanbrengen tot een admin dit heeft goedgekeurd of teruggezet.',
    'weekly.noEntries': 'Geen Invoeren',
    'weekly.noEntriesToCopy': 'De vorige dag heeft geen invoeren om te kopi├½ren.',
    'weekly.noValidEntriesToCopy': 'Geen geldige invoeren om te kopi├½ren.',
    'weekly.exportSuccessful': 'Export Succesvol',
    'weekly.exportSuccessfulDescription': 'Week {weekNumber} invoeren ge├½xporteerd naar {filename} met {dayCount} dag bladen',
    'weekly.sendWeekToEmail': 'Verstuur Week naar Email',
    'weekly.sendingEmail': 'Versturen...',
    'weekly.emailSentSuccess': 'Week succesvol verzonden naar {email}',
    'weekly.emailSentSuccessDescription': 'Week {weekNumber} {year} is verzonden via email',
    'weekly.emailSentError': 'Fout bij verzenden: {error}',
    'weekly.switchToOriginal': 'Schakel naar originele weergave',
    'weekly.switchToSimple': 'Schakel naar eenvoudige weergave',
    'weekly.original': 'Origineel',
    'weekly.simple': 'Eenvoudig',
    'weekly.editing': 'BEWERKEN',
    'weekly.alreadyConfirmed': 'Al Bevestigd',
    'weekly.alreadyConfirmedDescription': 'Deze week is al bevestigd.',
    'weekly.failedToConfirmWeek': 'Kon week niet bevestigen.',
    'weekly.updated': 'Bijgewerkt!',
    'weekly.employeeName': 'Medewerker Naam:',
    'weekly.date': 'Datum:',
    'weekly.weekNumber': 'Week Nummer:',
    'weekly.year': 'Jaar:',
    'weekly.projectWorkOrder': 'Project Werkorder',
    'weekly.hoursWorked': 'Gewerkte Uren',
    'weekly.kilometers': 'Kilometers',
    'weekly.sunday': 'Zondag',
    'weekly.monday': 'Maandag',
    'weekly.tuesday': 'Dinsdag',
    'weekly.wednesday': 'Woensdag',
    'weekly.thursday': 'Donderdag',
    'weekly.friday': 'Vrijdag',
    'weekly.saturday': 'Zaterdag',
    'weekly.total': 'Totaal per dag',
    'daily.total': 'Dag Totaal',
    'Confirm.Week': 'Bevestig Week',
    'weekly.confirm': 'Bevestigen',
    'weekly.confirmNote': 'Zodra je deze week bevestigt, kun je geen wijzigingen meer aanbrengen.',
    'weekly.confirmReminder': 'Je hebt invoeren voor deze week ingevuld. Vergeet niet om de week te bevestigen wanneer je klaar bent.',
    'weekly.weekLockedMessage': '✓ Deze week is bevestigd en vergrendeld. Neem contact op met een admin als je wijzigingen moet maken.',
    'admin.weekReview.addCommentHint': 'Voeg een comment toe zodat de gebruiker weet wat er aangepast moet worden.',
    'admin.weekReview.commentPlaceholder': 'Comment...',
    'admin.weekReview.emailFailedTitle': 'Email mislukt',
    'admin.weekReview.emailFailedDescription': 'Actie opgeslagen, maar email kon niet worden verzonden. Controleer Edge Function logs en secrets.',
    'admin.weekReview.approvedToastTitle': 'Week goedgekeurd',
    'admin.weekReview.approvedToastDescription': 'De week is goedgekeurd.',
    'admin.weekReview.rejectedToastTitle': 'Week afgekeurd',
    'admin.weekReview.rejectedToastDescription': 'De week is afgekeurd en ontgrendeld voor de gebruiker.',
    'weekly.work': 'Werk',
    'workType.10': 'Werk',
    'workType.11': 'Productie',
    'workType.12': 'Administratie',
    'workType.13': 'Tekenen',
    'workType.14': 'Beurs',
    'workType.15': 'Commercieel',
    'workType.16': 'Telefoonondersteuning',
    'workType.17': 'Intern BAMPRO',
    'workType.20': 'Thuis-Werk',
    'workType.21': 'Werk-Werk',
    'workType.22': 'Laden',
    'workType.23': 'Wachten',
    'workType.30': 'Ziek',
    'workType.31': 'Vrije Dag/Vakantie',
    'workType.32': 'Dokter',
    'workType.33': 'Begrafenis/Bruiloft',
    'workType.34': 'Magazijn',
    'workType.35': 'Pauze',
    'workType.36': 'Training',
    'workType.37': 'Vergadering',
    'workType.38': 'Feestdag',
    'workType.39': 'Tijd voor Tijd (ADV)',
    'workType.40': 'Genomen Tijd-voor-Tijd (TFT)',
    'workType.100': 'Remote',
    'weekly.fill.all.entries': 'Vul alle weekdagen (maandag-vrijdag) in voordat je bevestigt.',
    'weekly.fill.missing.entries': 'Vul ontbrekende weekdagen (maandag-vrijdag) in voordat je bevestigt.',
    
    
    
    // View Hours
    'viewHours.title': 'Ingevulde Uren',
    'viewHours.errorFetching': 'Fout bij ophalen van uren',
    'viewHours.noEntries': 'Geen uren gevonden voor deze week',
    'viewHours.noEntriesForDay': 'Geen uren voor deze dag',
    'viewHours.project': 'Project',
    'viewHours.workType': 'Werk Type',
    'viewHours.time': 'Tijd',
    'viewHours.hours': 'Uren',
    'viewHours.total': 'Totaal',
    'viewHours.weekTotal': 'Week Totaal',
    
    // Admin Panel
    'admin.title': 'Beheer Paneel',
    'admin.addUser': 'Gebruiker Toevoegen',
    'admin.email': 'Email',
    'admin.name': 'Naam',
    'admin.password': 'Wachtwoord',
    'admin.passwordPlaceholder': 'Min. 6 tekens',
    'admin.passwordMinLength': 'Wachtwoord moet minimaal 6 tekens lang zijn.',
    'admin.isAdmin': 'Admin',
    'admin.mustChangePassword': 'Moet wachtwoord wijzigen',
    'admin.createUser': 'Gebruiker Toevoegen',
    'admin.allUsers': 'Bestaande Gebruikers',
    'admin.pendingApproval': 'Wachtend op Goedkeuring',
    'admin.approve': 'Goedkeuren',
    'admin.reject': 'Afwijzen',
    'admin.resetPassword': 'Reset Wachtwoord',
    'admin.daysOff': 'Vrije Dagen',
    'admin.confirmedWeeks': 'Bevestigde Weken',
    'admin.approveWeek': 'Goedkeuren',
    'admin.reopenWeek': 'Heropen',
    'admin.weeksToReview': 'Weken om te Beoordelen',
    'admin.unknownUser': 'Onbekende gebruiker',
    'admin.totalHours': 'Totaal: {hours} uren ({entries} entries)',
    'admin.approveButton': 'Goedkeuren',
    'admin.rejectButton': 'Afwijzen',
    'admin.unlockButton': 'Ontgrendelen',
    'admin.viewUserWeeklyEntries': 'Bekijk Gebruiker Wekelijkse Entries',
    'admin.noConfirmedWeeks': 'Nog geen bevestigde weken.',
    'admin.noEntriesForUser': 'Geen entries gevonden voor deze gebruiker.',
    'admin.youCannotDeleteOwnAccount': 'Je kunt je eigen account niet verwijderen.',
    'admin.youCannotDeleteSuperAdmin': 'Je kunt de super admin niet verwijderen.',
    'admin.deleteUser': 'Verwijder gebruiker',
    'admin.oneDayEqualsEightHours': '(1 dag = 8 uren)',
    'admin.approvedStatus': 'Goedgekeurd',
    'admin.rejectedStatus': 'Afgewezen',
    'admin.pendingReviewStatus': 'In Afwachting van Beoordeling',
    'admin.sendReminder': 'Stuur Timesheet Herinnering',
    'admin.sendReminderDescription': 'Selecteer een of meer gebruikers om een herinnering te sturen om hun uren in te vullen voor een specifieke week.',
    'admin.selectUsers': 'Selecteer Gebruikers',
    'admin.week': 'Week',
    'admin.entries': 'entries',
    'admin.status': 'Status',
    'admin.weekNumber': 'Week Nummer',
    'admin.weekNumberPlaceholder': 'bijv. 51',
    'admin.year': 'Jaar',
    'admin.sendReminderButton': 'Stuur Herinnering',
    'admin.approved': 'Goedgekeurd',
    'admin.daysOffLeft': 'Vrije Dagen Over',
    'admin.actions': 'Acties',
    'admin.noUsers': 'Geen gebruikers beschikbaar',
    'admin.viewUserEntries': 'Bekijk Gebruiker Wekelijkse Entries',
    'admin.allConfirmedWeeks': 'Alle Bevestigde Weken',
    'admin.timebuzzerIntegration': 'Timebuzzer Integratie',
    'admin.timebuzzerDescription': 'Sync tijd entries van Timebuzzer naar je timesheet. Zorg ervoor dat gebruikers en projecten eerst gemapped zijn in de database.',
    'admin.testAPI': 'Test API',
    'admin.loadActivities': 'Laad Activiteiten van Timebuzzer',
    'admin.filterByUser': 'Filter op Gebruiker (Optioneel)',
    'admin.filterByUserDescription': 'Selecteer een gebruiker om Timebuzzer API te testen voor die specifieke gebruiker. Laat leeg om voor alle gebruikers te testen.',
    'admin.allUsersDefault': 'Alle gebruikers (standaard)',
    'admin.noteMapping': 'Let op: Gebruikers en projecten moeten gemapped zijn met Timebuzzer IDs in de database voordat je sync.',
    'admin.selectActivities': 'Selecteer Activiteiten om Toe te Voegen',
    'admin.selectAll': 'Selecteer Alles',
    'admin.deselectAll': 'Deselecteer Alles',
    'admin.addSelectedActivities': 'Voeg Geselecteerde Activiteiten Toe aan Wekelijkse Entries',
    'admin.activitiesLoaded': 'Activiteiten Geladen',
    'admin.foundActivities': 'Gevonden {count} activiteiten. Selecteer welke je wilt toevoegen aan wekelijkse entries.',
    'admin.noActivities': 'Geen Activiteiten',
    'admin.noActivitiesFound': 'Geen activiteiten gevonden voor deze week',
    'admin.mappingRequired': 'Mapping Vereist',
    'admin.missingUserMappings': 'Ontbrekende Gebruiker Mappings ({count})',
    'admin.missingProjectMappings': 'Ontbrekende Project Mappings ({count})',
    'admin.updateUserSQL': 'Voor Gebruikers: UPDATE users SET timebuzzer_user_id = \'{id}\' WHERE email = \'{email}\';',
    'admin.updateProjectSQL': 'Voor Projecten: UPDATE projects SET timebuzzer_project_id = \'{id}\' WHERE name = \'{name}\';',
    'admin.activitiesSkipped': 'Activiteiten worden overgeslagen vanwege ontbrekende gebruiker of project mappings. Gebruik de SQL statements hieronder om de mappings toe te voegen.',
    'admin.yes': 'Ja',
    'admin.no': 'Nee',
    'admin.add': 'Toevoegen',
    'admin.subtract': 'Aftrekken',
    'admin.hours': 'Uren',
    'admin.hoursTaken': 'Uren Genomen',
    'admin.daysOffOverview': 'Vrije Dagen Overzicht',
    'admin.daysOffOverviewDescription': 'Overzicht van alle vrije dagen die gebruikers nog over hebben voor het huidige jaar.',
    'admin.newPassword': 'Nieuw wachtwoord',
    'admin.date': 'Datum',
    'admin.workType': 'Werk Type',
    'admin.description': 'Beschrijving',
    'admin.startEnd': 'Start - Eind',
    'admin.total': 'Totaal per dag',
    'admin.userType': 'Gebruiker Type',
    'admin.userType.user': 'Gebruiker',
    'admin.userType.administratie': 'Administratie',
    'admin.userType.admin': 'Admin',
    'admin.userType.weeklyOnly': 'Alleen Wekelijkse Invoer',
    'admin.userType.superAdmin': 'Super admin',
    'admin.errors': 'Fouten',
    'admin.errorLogs': 'Fout Logs',
    'admin.deleteRequests': 'Verwijderverzoeken',
    'admin.deleteRequestTitle': 'Verwijderverzoeken',
    'admin.deleteRequestDescription': 'Beoordeel en beheer verzoeken van administratie-gebruikers om gebruikers te verwijderen.',
    'admin.deleteRequestLoading': 'Verwijderverzoeken laden...',
    'admin.noDeleteRequests': 'Geen openstaande verwijderverzoeken',
    'admin.deleteRequestUserToDelete': 'Gebruiker om te verwijderen:',
    'admin.deleteRequestRequestedBy': 'Verzoek ingediend door:',
    'admin.deleteRequestApprove': 'Goedkeuren en Verwijderen',
    'admin.deleteRequestReject': 'Afwijzen',
    'admin.deleteRequestSent': 'Verzoek ingediend',
    'admin.deleteRequestSentDescription': 'Het verzoek om {email} te verwijderen is naar de super admin gestuurd.',
    'admin.deleteRequestApproved': 'Verzoek goedgekeurd',
    'admin.deleteRequestApprovedDescription': '{email} is verwijderd.',
    'admin.deleteRequestRejected': 'Verzoek afgewezen',
    'admin.deleteRequestRejectedDescription': 'Verzoek om {email} te verwijderen is afgewezen.',
    'admin.cannotChangeUserType': 'Actie niet toegestaan',
    'admin.cannotChangeUserTypeDescription': 'Administratie-gebruikers kunnen geen user types wijzigen.',
    'admin.cannotInviteNonUser': 'Actie niet toegestaan',
    'admin.cannotInviteNonUserDescription': 'Administratie-gebruikers kunnen alleen gebruikers met type \'user\' uitnodigen.',
    'admin.deleteRequest.approveConfirmTitle': 'Verzoek Goedkeuren',
    'admin.deleteRequest.approveConfirmDescription': 'Weet je zeker dat je deze gebruiker wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
    'admin.deleteRequest.rejectConfirmTitle': 'Verzoek Afwijzen',
    'admin.deleteRequest.rejectConfirmDescription': 'Weet je zeker dat je dit verzoek wilt afwijzen?',
    'admin.deleteRequest.pendingRequests': 'openstaande verzoeken',
    'admin.deleteRequest.pendingRequest': 'openstaand verzoek',
    'admin.deleteRequest.feedbackApproved': 'Verzoek goedgekeurd',
    'admin.deleteRequest.feedbackApprovedDescription': 'Je verzoek om {email} te verwijderen is goedgekeurd. {email} is verwijderd uit het systeem.',
    'admin.deleteRequest.feedbackRejected': 'Verzoek afgewezen',
    'admin.deleteRequest.feedbackRejectedDescription': 'Je verzoek om {email} te verwijderen is afgewezen. {email} blijft actief in het systeem.',
    'admin.refresh': 'Verversen',
    'admin.deleteResizeObserverErrors': 'Verwijder ResizeObserver Fouten',
    'admin.deleteAllErrors': 'Verwijder Alle Fouten',
    'admin.unresolved': 'Onopgelost',
    'admin.resolved': 'Opgelost',
    'admin.allSeverities': 'Alle Ernstniveaus',
    'admin.resolve': 'Oplossen',
    'admin.error': 'Fout',
    'admin.warning': 'Waarschuwing',
    'admin.info': 'Info',
    'admin.deleteErrorLog': 'Weet je zeker dat je dit fout log wilt verwijderen?',
    'admin.deleteAllErrorsConfirm': 'Weet je zeker dat je ALLE fout logs wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
    'admin.deleteResizeObserverErrorsConfirm': 'Weet je zeker dat je alle ResizeObserver fouten wilt verwijderen?',
    'admin.errorLogDeleted': 'Fout log verwijderd',
    'admin.allErrorLogsDeleted': 'Alle fout logs verwijderd',
    'admin.errorLogsDeletedCount': 'Alle fout logs verwijderd ({deleted} verwijderd, {remaining} over)',
    'admin.resizeObserverErrorsDeleted': 'Alle ResizeObserver fouten verwijderd',
    'admin.noResizeObserverErrors': 'Geen ResizeObserver fouten gevonden om te verwijderen',
    'admin.failedToFetchErrorLogs': 'Kon fout logs niet ophalen',
    'admin.failedToFetchErrorLogsRLS': 'Kon fout logs niet ophalen. Controleer RLS policies.',
    'admin.noErrorLogsFound': 'Geen fout logs gevonden om te verwijderen. Als fouten nog steeds zichtbaar zijn, kan er een RLS policy probleem zijn. Voer fix_error_logs_rls.sql uit in Supabase SQL Editor.',
    'admin.alreadyConfirmed': 'Al Bevestigd',
    'admin.alreadyConfirmedText': 'Deze week is al bevestigd.',
    'admin.weekConfirmed': 'Week Bevestigd',
    'admin.weekConfirmedAndLocked': 'Deze week is bevestigd en vergrendeld. Je kunt geen wijzigingen meer aanbrengen.',
    'admin.weekLocked': 'Week Vergrendeld',
    'admin.weekLockedText': 'Deze week is bevestigd en kan niet worden gewijzigd.',
    'admin.missingInformation': 'Ontbrekende Informatie',
    'admin.selectWeekAndYear': 'Selecteer een week en jaar.',
    'admin.existingUsers': 'Bestaande Gebruikers',
    'admin.searchWeeks': 'Zoek week',
    'admin.allStatuses': 'Status',
    'admin.noWeeksMatchFilters': 'Geen weken komen overeen met de filters.',
    'admin.user': 'Gebruiker',
    'admin.dateRange': 'Datumbereik',
    
    // Auth/Login
    'auth.loginSuccessful': 'Login Succesvol',
    'auth.loginFailed': 'Login Mislukt',
    'auth.welcome': 'Welkom, {name}!',
    'auth.welcomeRememberMe': 'Welkom, {name}! Je blijft 7 dagen ingelogd.',
    'auth.pleaseEnterCredentials': 'Voer geldige inloggegevens in',
    'auth.userNotFound': 'Gebruiker niet gevonden',
    'auth.incorrectPassword': 'Onjuist wachtwoord',
    'auth.accountPendingApproval': 'Account Wacht op Goedkeuring',
    'auth.accountPendingApprovalText': 'Je account wacht op goedkeuring van een beheerder. Neem contact op met een beheerder.',
    'auth.missingInformation': 'Ontbrekende Informatie',
    'auth.missingInformationText': 'Email, naam en wachtwoord zijn verplicht om een gebruiker aan te maken.',
    'auth.onlyBamproEmail': 'Alleen BAMPRO Email Toegestaan',
    'auth.onlyBamproEmailText': 'Je kunt alleen een account aanmaken met een @bampro.nl email adres. Voor andere email adressen moet je door een admin worden uitgenodigd.',
    'auth.passwordTooShort': 'Wachtwoord te kort',
    'auth.passwordTooShortText': 'Wachtwoord moet minimaal 6 tekens lang zijn.',
    'auth.accountCreated': 'Account aangemaakt',
    'auth.accountCreatedText': 'Je account is aangemaakt en wacht op goedkeuring van een administrator. Je kunt inloggen zodra een administrator je account heeft goedgekeurd.',
    'auth.errorCreatingUser': 'Fout bij aanmaken gebruiker',
    'auth.enterEmail': 'Voer een email adres in.',
    'auth.userNotFoundReset': 'Gebruiker niet gevonden. Controleer je email adres.',
    'auth.resetPassword': 'Wachtwoord Resetten',
    'auth.resetPasswordDescription': 'Voer je email adres in om een wachtwoord reset link te ontvangen.',
    'auth.sendResetLink': 'Verstuur Reset Link',
    'auth.sending': 'Verzenden...',
    'auth.stayLoggedIn': 'Blijf ingelogd.',
    'auth.forgotPassword': 'Wachtwoord Vergeten?',
    'auth.login': 'Login',
    'auth.loginToStart': 'Login om tijd te registreren',
    'auth.email': 'Email',
    'auth.password': 'Wachtwoord',
    'auth.enterYourEmail': 'Voer je email in',
    'auth.enterYourPassword': 'Voer je wachtwoord in',
    'auth.resetEmailSent': 'Reset email verstuurd',
    'auth.resetEmailSentText': 'Een password reset link is verstuurd naar {email}. Check je inbox.',
    'auth.resetEmailError': 'Kon geen password reset email versturen. De password-reset Edge Function is mogelijk niet gedeployed. Neem contact op met een administrator.',
    'auth.resetEmailSuccess': 'Password reset email is verstuurd! Check je inbox (en spam folder) voor de reset link. De link is 1 uur geldig.',
    'auth.holdToShowPassword': 'Houd ingedrukt om wachtwoord te tonen',
    'auth.error': 'Fout',
    'auth.unknownError': 'Onbekende fout',
    'auth.checkConsole': 'Check de browser console (F12) voor meer details.',
    'auth.loggedOut': 'Uitgelogd',
    'auth.loggedOutText': 'Je bent succesvol uitgelogd.',
    
    // Weekly Entry Export
    'weekly.exportFailed': 'Export Mislukt',
    'weekly.noData': 'Geen Data',
    'weekly.noEntriesForWeek': 'Geen entries gevonden voor deze week.',
    
    // Time Overview
    'overview.title': 'Project Overzicht',
    'overview.subtitle': 'Uren per project - {name} uren',
    'overview.allTime': 'Alle tijd',
    'overview.thisMonth': 'Deze maand',
    'overview.thisWeek': 'Deze week',
    'overview.totalHours': 'Totaal Uren',
    'overview.projects': 'Projecten',
    'overview.avgPerProject': 'Gemiddeld per Project',
    'overview.project': 'Project',
    'overview.entries': 'Entries',
    'overview.percentage': 'Percentage',
    'overview.visualization': 'Visualisatie',
    'overview.total': 'TOTAAL',
    'overview.loading': 'Laden...',
    'overview.noHoursFound': 'Geen uren gevonden voor de geselecteerde periode.',
    
    // Admin Panel Tabs
    'admin.tab.users': 'Gebruikers',
    'admin.tab.weeks': 'Weken',
    'admin.tab.reminders': 'Herinneringen',
    'admin.tab.export': 'Exporteren',
    'admin.tab.overtime': 'Overuren',
    'admin.tab.timebuzzer': 'Timebuzzer',
    
    // Overtime
    'overtime.title': 'Overuren Tracking',
    'overtime.description': 'Bekijk uw overuren met percentage breakdown. Een normale werkdag (maandag t/m vrijdag) is 8 uur.',
    'overtime.percentageRules': 'Percentage regels: Na 8 uur op weekdagen: 9e & 10e uur = 125%, elk uur na 10 uur = 150%. Zaterdag = 150% (alle uren). Zondag = 200% (alle uren).',
    'overtime.period': 'Periode',
    'overtime.week': 'Week',
    'overtime.month': 'Maand',
    'overtime.year': 'Jaar',
    'overtime.all': 'Alles',
    'overtime.calculate': 'Bereken Overuren',
    'overtime.calculating': 'Berekenen...',
    'overtime.totalOvertime': 'Totaal Overuren',
    'overtime.percentageBreakdown': 'Overuren per Percentage:',
    'overtime.hours125': '9e & 10e uur (weekdagen)',
    'overtime.hours150': 'Na 10e uur & Zaterdag',
    'overtime.hours200': 'Zondag',
    'overtime.perDayBreakdown': 'Overuren per Percentage:',
    'overtime.details': 'Details',
    'overtime.entries': 'entries',
    'overtime.project': 'Project',
    'overtime.workType': 'Werk Type',
    'overtime.time': 'Tijd',
    'overtime.hours': 'Uren',
    'overtime.notes': 'Notities',
    'overtime.weekend': 'Weekend',
    'overtime.totalHours': 'h totaal (alle uren zijn overuren)',
    'overtime.totalHoursNormal': 'h totaal - {normalHours}h normaal',
    'overtime.clickToCalculate': 'Klik op "Bereken Overuren" om de overuren te berekenen.',
    'overtime.overnightTitle': 'Overnachtingen',
    'overtime.overnightCount': 'Totaal overnachtingen',
    'overtime.overnightNone': 'Geen overnachtingen in deze periode.',
    'overtime.missingInformation': 'Ontbrekende Informatie',
    'overtime.selectWeekAndYear': 'Selecteer een week en jaar.',
    'overtime.error': 'Fout',
    'overtime.failedToCalculate': 'Kon overuren niet berekenen',
    'nav.overtime': 'Overuren',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fout',
    'common.success': 'Succes',
    'common.cancel': 'Annuleren',
    'common.close': 'Sluiten',
    'common.save': 'Opslaan',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.confirm': 'Bevestigen',
    'common.user': 'Gebruiker',

    // Bug Report
    'View.manage': 'Bekijk en beheer bug rapporten ingediend door gebruikers',




  },
  en: {
    // Navigation
    'nav.weekly': 'Weekly Entry',
    'nav.viewHours': 'View Hours',
    'nav.projects': 'Projects',
    'nav.export': 'Export',
    'nav.admin': 'Admin',
    'nav.weeks': 'Weeks',
    'nav.reportBug': 'Report Bug',
    'nav.overview': 'Overview',
    'nav.welcome': 'Welcome',
    'nav.logout': 'Logout',
    'nav.clickToViewProfile': 'Click to view and edit your profile',
    
    // Project Management
    'project.addNew': 'Add New Project',
    'project.create': 'Create a new project for time tracking',
    'project.name': 'Project Name',
    'project.namePlaceholder': 'Enter project name',
    'project.client': 'Client',
    'project.clientPlaceholder': 'Client name',
    'project.description': 'Description',
    'project.descriptionPlaceholder': 'Project description...',
    'project.createButton': 'Create Project',
    'project.active': 'Active Projects',
    'project.manage': 'Manage and track your projects',
    'project.viewDetails': 'View Details',
    'project.close': 'Close',
    'project.reopen': 'Reopen',
    'project.delete': 'Delete',
    'project.deleteConfirm': 'Delete Project',
    'project.deleteConfirmText': 'Are you sure you want to delete "{name}"? All related timesheet entries will also be deleted. This action cannot be undone.',
    'project.cancel': 'Cancel',
    'project.deleted': 'Project Deleted',
    'project.deletedText': '{name} has been successfully deleted. All related timesheet entries have also been deleted.',
    'project.closed': 'Project Closed',
    'project.reopened': 'Project Reopened',
    'project.closedText': '{name} has been closed. No more hours can be added to it.',
    'project.reopenedText': '{name} has been reopened. Hours can be added to it again.',
    'project.status.active': 'Active',
    'project.status.closed': 'Closed',
    'project.status.completed': 'Completed',
    'project.status.onHold': 'On Hold',
    'project.hoursLogged': '{hours}h logged',
    'project.members': 'members',
    'project.details': 'Project Details: {name}',
    'project.allEntries': 'All time entries for this project',
    'project.noEntries': 'No time entries yet.',
    
    // Weekly Entry
    'weekly.workType': 'Work Type',
    'weekly.project': 'Project',
    'weekly.hours': 'Hours',
    'weekly.lunch': 'Lunch',
    'weekly.startTime': 'Start Time',
    'weekly.endTime': 'End Time',
    'weekly.submit': 'Submit',
    'weekly.submitAll': 'Submit All Days',
    'weekly.submitDay': 'Submit Day',
    'weekly.add': 'Add',
    'weekly.confirmed': 'This week is confirmed. You cannot make any changes until an admin has approved or reset it.',
    
    // Export
    'export.title': 'Export Timesheet Data',
    'export.description': 'Export timesheet data to Excel for reporting and analysis',
    'export.selectUser': 'Select User (optional)',
    'export.allUsers': 'All users',
    'export.selectUserHelp': 'Leave empty to export all users, or select a specific user.',
    'export.allData': 'Export All Data',
    'export.dateRange': 'Export Date Range',
    'export.weekNumber': 'Export Week Number',
    'export.perUser': 'Export Per User',
    'export.selectPeriod': 'Select Period',
    'export.selectDay': 'Select Day',
    'export.selectWeek': 'Select Week (every day in the week)',
    'export.selectMonth': 'Select Month (every day in the month)',
    'export.selectYear': 'Select Year (every day in the year)',
    'export.exporting': 'Exporting...',
    'export.day': 'Day',
    'export.week': 'Week',
    'export.month': 'Month',
    'export.year': 'Year',
    'export.note': 'Note:',
    'export.adminNote': 'Admins can export all data, select a date range, or export per user. Select a user to export only that user, or leave empty for all users.',
    'export.userNote': 'Select a period and date to export your hours to Excel.',
    'export.weekPlaceholder': 'Week',
    'export.yearPlaceholder': 'Year',
    'export.overtimeSummary': 'Overtime Summary',
    'export.overtimeTotal': 'Total overtime',
    'export.overtime125': 'Overtime 125%',
    'export.overtime150': 'Overtime 150%',
    'export.overtime200': 'Overtime 200%',
    'export.overnightStays': 'Overnight stays',
    'export.overnightDates': 'Overnight dates',
    
    // Weekly Entry
    'weekly.viewMode.cards': 'Cards',
    'weekly.viewMode.overview': 'Overview',
    'weekly.daysOff': 'Days Off Remaining',
    'weekly.confirmWeek': 'Confirm Week',
    'weekly.confirmWeekText': 'Are you sure you want to confirm this week? After confirmation, you cannot make changes.',
    'weekly.weekConfirmed': 'Week Confirmed',
    'weekly.weekConfirmedText': 'This week is confirmed and cannot be changed anymore.',
    'weekly.weekConfirmedSendEmailPrompt': 'Your week has been confirmed and locked. Would you like to send the Excel file to administratie?',
    'weekly.skip': 'Skip',
    'weekly.type': 'Type',
    'weekly.projectPlaceholder': 'Project',
    'weekly.title': 'Weekly Calendar Entry',
    'weekly.week': 'Week',
    'weekly.prev': 'Prev',
    'weekly.next': 'Next',
    'weekly.selectWeek': 'Select Week',
    'weekly.exportWeek': 'Export Week to Excel',
    'weekly.daysOffRemaining': 'Days Off Remaining',
    'weekly.daysOffLeft': 'You have {days} days off left this year.',
    'weekly.weekOverview': 'Week Overview',
    'weekly.dayView': 'Day View',
    'weekly.entry': 'entry',
    'weekly.entries': 'entries',
    'weekly.day': 'Day',
    'weekly.van': 'From',
    'weekly.tot': 'To',
    'weekly.from': 'From',
    'weekly.to': 'To',
    'weekly.actions': 'Actions',
    'weekly.submittedEntries': 'Submitted Entries:',
    'weekly.addCustomProject': 'Add custom project',
    'weekly.selectWorkType': 'Select work type...',
    'weekly.selectProject': 'Select project...',
    'weekly.clear': 'Clear',
    'weekly.startPlaceholder': 'Start (e.g. 08:10)',
    'weekly.endPlaceholder': 'End (e.g. 17:45)',
    'weekly.hoursPlaceholder': 'h',
    'weekly.copyPrevious': 'Copy Previous',
    'weekly.searchWorkType': 'Search work type...',
    'weekly.noWorkTypeFound': 'No work type found.',
    'weekly.switchToOriginalView': 'Switch to original view',
    'weekly.addEntry': 'Add Entry',
    'weekly.searchProject': 'Search project or type to create new...',
    'weekly.noProjectFound': 'No project found. Press Enter to create',
    'weekly.noProjectsFound': 'No projects found.',
    'weekly.create': 'Create',
    'weekly.time': 'Time',
    'weekly.save': 'Save',
    'weekly.editEntry': 'Edit entry',
    'weekly.deleteEntry': 'Delete entry',
    'weekly.fullDayOff': 'Full day off (8 hours)',
    'weekly.overnightStay': 'Overnight stay (didn’t sleep at home)',
    'weekly.total': 'Total per day',
    'weekly.weekConfirmedWarning': 'This week is confirmed. You cannot make any more changes until an admin has approved or reset it.',
    'weekly.noEntries': 'No Entries',
    'weekly.noEntriesToCopy': 'The previous day has no entries to copy.',
    'weekly.noValidEntriesToCopy': 'No valid entries to copy.',
    'weekly.exportSuccessful': 'Export Successful',
    'weekly.exportSuccessfulDescription': 'Week {weekNumber} entries exported to {filename} with {dayCount} day sheets',
    'weekly.sendWeekToEmail': 'Send Week to Email',
    'weekly.sendingEmail': 'Sending...',
    'weekly.emailSentSuccess': 'Week successfully sent to {email}',
    'weekly.emailSentSuccessDescription': 'Week {weekNumber} {year} has been sent via email',
    'weekly.emailSentError': 'Error sending email: {error}',
    'weekly.switchToOriginal': 'Switch to original view',
    'weekly.switchToSimple': 'Switch to simple view',
    'weekly.original': 'Original',
    'weekly.simple': 'Simple',
    'weekly.editing': 'EDITING',
    'weekly.alreadyConfirmed': 'Already Confirmed',
    'weekly.alreadyConfirmedDescription': 'This week is already confirmed.',
    'weekly.failedToConfirmWeek': 'Failed to confirm week.',
    'weekly.updated': 'Updated!',
    'weekly.employeeName': 'Employee Name:',
    'weekly.date': 'Date:',
    'weekly.weekNumber': 'Week Number:',
    'weekly.year': 'Year:',
    'weekly.projectWorkOrder': 'Project Work Order',
    'weekly.hoursWorked': 'Hours Worked',
    'weekly.kilometers': 'Kilometers',
    'weekly.sunday': 'Sunday',
    'weekly.monday': 'Monday',
    'weekly.tuesday': 'Tuesday',
    'weekly.wednesday': 'Wednesday',
    'weekly.thursday': 'Thursday',
    'weekly.friday': 'Friday',
    'weekly.saturday': 'Saturday',
    'daily.total': 'Day Total',
    'Confirm.Week': 'Confirm Week',
    'weekly.confirm': 'Confirm',
    'weekly.confirmNote': 'Once you confirm this week, you will not be able to make any changes.',
    'weekly.confirmReminder': 'You have filled in entries for this week. Don\'t forget to confirm the week when you\'re done.',
    'weekly.weekLockedMessage': '✓ This week has been confirmed and locked. Contact an admin if you need to make changes.',
    'admin.weekReview.addCommentHint': 'Add a comment so the user knows what to fix.',
    'admin.weekReview.commentPlaceholder': 'Comment...',
    'admin.weekReview.emailFailedTitle': 'Email failed',
    'admin.weekReview.emailFailedDescription': 'Action saved, but email could not be sent. Check Edge Function logs and secrets.',
    'admin.weekReview.approvedToastTitle': 'Week approved',
    'admin.weekReview.approvedToastDescription': 'The week has been approved.',
    'admin.weekReview.rejectedToastTitle': 'Week rejected',
    'admin.weekReview.rejectedToastDescription': 'The week has been rejected and unlocked for the user.',
    'weekly.work': 'Work',
    'workType.10': 'Work',
    'workType.11': 'Production',
    'workType.12': 'Administration',
    'workType.13': 'Drawing',
    'workType.14': 'Trade Fair',
    'workType.15': 'Commercial',
    'workType.16': 'Telephone Support',
    'workType.17': 'Internal BAMPRO',
    'workType.20': 'Home-Work',
    'workType.21': 'Work-Work',
    'workType.22': 'Loading',
    'workType.23': 'Waiting',
    'workType.30': 'Sick',
    'workType.31': 'Day Off/Vacation',
    'workType.32': 'Doctor',
    'workType.33': 'Funeral/Wedding',
    'workType.34': 'Warehouse',
    'workType.35': 'Break',
    'workType.36': 'Training',
    'workType.37': 'Meeting',
    'workType.38': 'Public Holiday',
    'workType.39': 'Time Off in Lieu (ADV)',
    'workType.40': 'Taken Time-for-Time (TFT)',
    'workType.100': 'Remote',
    'weekly.fill.all.entries': 'Please fill in entries for all weekdays (Monday-Friday) before confirming.',
    'weekly.fill.missing.entries': 'Please fill in entries for the missing weekdays (Monday-Friday) before confirming.',
    
    
    
    
    // View Hours
    'viewHours.title': 'View Hours',
    'viewHours.errorFetching': 'Error fetching hours',
    'viewHours.noEntries': 'No hours found for this week',
    'viewHours.noEntriesForDay': 'No hours for this day',
    'viewHours.project': 'Project',
    'viewHours.workType': 'Work Type',
    'viewHours.time': 'Time',
    'viewHours.hours': 'Hours',
    'viewHours.total': 'Total',
    'viewHours.weekTotal': 'Week Total',
    
    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.addUser': 'Add User',
    'admin.email': 'Email',
    'admin.name': 'Name',
    'admin.password': 'Password',
    'admin.isAdmin': 'Admin',
    'admin.mustChangePassword': 'Must change password',
    'admin.createUser': 'Create User',
    'admin.allUsers': 'All Users',
    'admin.pendingApproval': 'Pending Approval',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.resetPassword': 'Reset Password',
    'admin.daysOff': 'Days Off',
    'admin.confirmedWeeks': 'Confirmed Weeks',
    'admin.approveWeek': 'Approve',
    'admin.reopenWeek': 'Reopen',
    'admin.weeksToReview': 'Weeks to Review',
    'admin.unknownUser': 'Unknown user',
    'admin.totalHours': 'Total: {hours} hours ({entries} entries)',
    'admin.approveButton': 'Approve',
    'admin.rejectButton': 'Reject',
    'admin.unlockButton': 'Unlock',
    'admin.viewUserWeeklyEntries': 'View User Weekly Entries',
    'admin.noConfirmedWeeks': 'No confirmed weeks yet.',
    'admin.noEntriesForUser': 'No entries found for this user.',
    'admin.youCannotDeleteOwnAccount': 'You cannot delete your own account.',
    'admin.youCannotDeleteSuperAdmin': 'You cannot delete the super admin.',
    'admin.deleteUser': 'Delete user',
    'admin.oneDayEqualsEightHours': '(1 day = 8 hours)',
    'admin.approvedStatus': 'Approved',
    'admin.rejectedStatus': 'Rejected',
    'admin.pendingReviewStatus': 'Pending Review',
    'admin.sendReminder': 'Send Timesheet Reminder',
    'admin.sendReminderDescription': 'Select one or more users to send a reminder to fill in their hours for a specific week.',
    'admin.selectUsers': 'Select Users',
    'admin.week': 'Week',
    'admin.entries': 'entries',
    'admin.status': 'Status',
    'admin.weekNumber': 'Week Number',
    'admin.weekNumberPlaceholder': 'e.g. 51',
    'admin.year': 'Year',
    'admin.sendReminderButton': 'Send Reminder',
    'admin.approved': 'Approved',
    'admin.daysOffLeft': 'Days Off Left',
    'admin.actions': 'Actions',
    'admin.noUsers': 'No users available',
    'admin.viewUserEntries': 'View User Weekly Entries',
    'admin.allConfirmedWeeks': 'All Confirmed Weeks',
    'admin.timebuzzerIntegration': 'Timebuzzer Integration',
    'admin.timebuzzerDescription': 'Sync time entries from Timebuzzer to your timesheet. Make sure users and projects are mapped first in the database.',
    'admin.testAPI': 'Test API',
    'admin.loadActivities': 'Load Activities from Timebuzzer',
    'admin.filterByUser': 'Filter by User (Optional)',
    'admin.filterByUserDescription': 'Select a user to test Timebuzzer API for that specific user. Leave empty to test for all users.',
    'admin.allUsersDefault': 'All users (default)',
    'admin.noteMapping': 'Note: Users and projects must be mapped with Timebuzzer IDs in the database before you sync.',
    'admin.selectActivities': 'Select Activities to Add',
    'admin.selectAll': 'Select All',
    'admin.deselectAll': 'Deselect All',
    'admin.addSelectedActivities': 'Add Selected Activities to Weekly Entries',
    'admin.activitiesLoaded': 'Activities Loaded',
    'admin.foundActivities': 'Found {count} activities. Select which ones you want to add to weekly entries.',
    'admin.noActivities': 'No Activities',
    'admin.noActivitiesFound': 'No activities found for this week',
    'admin.mappingRequired': 'Mapping Required',
    'admin.missingUserMappings': 'Missing User Mappings ({count})',
    'admin.missingProjectMappings': 'Missing Project Mappings ({count})',
    'admin.updateUserSQL': 'For Users: UPDATE users SET timebuzzer_user_id = \'{id}\' WHERE email = \'{email}\';',
    'admin.updateProjectSQL': 'For Projects: UPDATE projects SET timebuzzer_project_id = \'{id}\' WHERE name = \'{name}\';',
    'admin.activitiesSkipped': 'Activities are being skipped due to missing user or project mappings. Use the SQL statements below to add the mappings.',
    'admin.passwordPlaceholder': 'Min. 6 characters',
    'admin.passwordMinLength': 'Password must be at least 6 characters long.',
    'admin.yes': 'Yes',
    'admin.no': 'No',
    'admin.add': 'Add',
    'admin.subtract': 'Subtract',
    'admin.hours': 'Hours',
    'admin.hoursTaken': 'Hours Taken',
    'admin.daysOffOverview': 'Days Off Overview',
    'admin.daysOffOverviewDescription': 'Overview of all users\' remaining days off for the current year.',
    'admin.newPassword': 'New password',
    'admin.date': 'Date',
    'admin.workType': 'Work Type',
    'admin.description': 'Description',
    'admin.startEnd': 'Start - End',
    'admin.total': 'Total per day',
    'admin.userType': 'User Type',
    'admin.userType.user': 'User',
    'admin.userType.administratie': 'Administratie',
    'admin.userType.admin': 'Admin',
    'admin.userType.weeklyOnly': 'Weekly Entry Only',
    'admin.userType.superAdmin': 'Super admin',
    'admin.errors': 'Errors',
    'admin.errorLogs': 'Error Logs',
    'admin.deleteRequests': 'Delete Requests',
    'admin.deleteRequestTitle': 'Delete Requests',
    'admin.deleteRequestDescription': 'Review and manage requests from administratie users to delete users.',
    'admin.deleteRequestLoading': 'Loading delete requests...',
    'admin.noDeleteRequests': 'No pending delete requests',
    'admin.deleteRequestUserToDelete': 'User to delete:',
    'admin.deleteRequestRequestedBy': 'Requested by:',
    'admin.deleteRequestApprove': 'Approve and Delete',
    'admin.deleteRequestReject': 'Reject',
    'admin.deleteRequestSent': 'Request submitted',
    'admin.deleteRequestSentDescription': 'The request to delete {email} has been sent to the super admin.',
    'admin.deleteRequestApproved': 'Request approved',
    'admin.deleteRequestApprovedDescription': '{email} has been deleted.',
    'admin.deleteRequestRejected': 'Request rejected',
    'admin.deleteRequestRejectedDescription': 'Request to delete {email} has been rejected.',
    'admin.cannotChangeUserType': 'Action not allowed',
    'admin.cannotChangeUserTypeDescription': 'Administratie users cannot change user types.',
    'admin.cannotInviteNonUser': 'Action not allowed',
    'admin.cannotInviteNonUserDescription': 'Administratie users can only invite users with type \'user\'.',
    'admin.deleteRequest.approveConfirmTitle': 'Approve Request',
    'admin.deleteRequest.approveConfirmDescription': 'Are you sure you want to delete this user? This action cannot be undone.',
    'admin.deleteRequest.rejectConfirmTitle': 'Reject Request',
    'admin.deleteRequest.rejectConfirmDescription': 'Are you sure you want to reject this delete request?',
    'admin.deleteRequest.pendingRequests': 'pending requests',
    'admin.deleteRequest.pendingRequest': 'pending request',
    'admin.deleteRequest.feedbackApproved': 'Request approved',
    'admin.deleteRequest.feedbackApprovedDescription': 'Your request to delete {email} has been approved. {email} has been removed from the system.',
    'admin.deleteRequest.feedbackRejected': 'Request rejected',
    'admin.deleteRequest.feedbackRejectedDescription': 'Your request to delete {email} has been rejected. {email} remains active in the system.',
    'admin.refresh': 'Refresh',
    'admin.deleteResizeObserverErrors': 'Delete ResizeObserver Errors',
    'admin.deleteAllErrors': 'Delete All Errors',
    'admin.unresolved': 'Unresolved',
    'admin.resolved': 'Resolved',
    'admin.allSeverities': 'All Severities',
    'admin.resolve': 'Resolve',
    'admin.error': 'Error',
    'admin.warning': 'Warning',
    'admin.info': 'Info',
    'admin.deleteErrorLog': 'Are you sure you want to delete this error log?',
    'admin.deleteAllErrorsConfirm': 'Are you sure you want to delete ALL error logs? This action cannot be undone.',
    'admin.deleteResizeObserverErrorsConfirm': 'Are you sure you want to delete all ResizeObserver errors?',
    'admin.errorLogDeleted': 'Error log deleted',
    'admin.allErrorLogsDeleted': 'All error logs deleted',
    'admin.errorLogsDeletedCount': 'All error logs deleted ({deleted} deleted, {remaining} remaining)',
    'admin.resizeObserverErrorsDeleted': 'All ResizeObserver errors deleted',
    'admin.noResizeObserverErrors': 'No ResizeObserver errors found to delete',
    'admin.failedToFetchErrorLogs': 'Failed to fetch error logs',
    'admin.failedToFetchErrorLogsRLS': 'Failed to fetch error logs. Check RLS policies.',
    'admin.noErrorLogsFound': 'No error logs found to delete. If errors are still visible, there might be an RLS policy issue. Please run fix_error_logs_rls.sql in Supabase SQL Editor.',
    'admin.alreadyConfirmed': 'Already Confirmed',
    'admin.alreadyConfirmedText': 'This week is already confirmed.',
    'admin.weekConfirmed': 'Week Confirmed',
    'admin.weekConfirmedAndLocked': 'This week has been confirmed and locked. You can no longer make changes.',
    'admin.weekLocked': 'Week Locked',
    'admin.weekLockedText': 'This week is confirmed and cannot be modified.',
    'admin.missingInformation': 'Missing Information',
    'admin.selectWeekAndYear': 'Please select a week and year.',
    'admin.searchWeeks': 'Search week',
    'admin.allStatuses': 'All Statuses',
    'admin.noWeeksMatchFilters': 'No weeks match the filters.',
    'admin.user': 'User',
    'admin.dateRange': 'Date Range',
    
    // Auth/Login
    'auth.loginSuccessful': 'Login Successful',
    'auth.loginFailed': 'Login Failed',
    'auth.welcome': 'Welcome, {name}!',
    'auth.welcomeRememberMe': 'Welcome, {name}! You will stay logged in for 7 days.',
    'auth.pleaseEnterCredentials': 'Please enter valid credentials',
    'auth.userNotFound': 'User not found',
    'auth.incorrectPassword': 'Incorrect password',
    'auth.accountPendingApproval': 'Account Pending Approval',
    'auth.accountPendingApprovalText': 'Your account is waiting for admin approval. Please contact an administrator.',
    'auth.missingInformation': 'Missing Information',
    'auth.missingInformationText': 'Email, name and password are required to create a user.',
    'auth.onlyBamproEmail': 'Only BAMPRO Email Allowed',
    'auth.onlyBamproEmailText': 'You can only create an account with a @bampro.nl email address. For other email addresses, you must be invited by an admin.',
    'auth.passwordTooShort': 'Password Too Short',
    'auth.passwordTooShortText': 'Password must be at least 6 characters long.',
    'auth.accountCreated': 'Account Created',
    'auth.accountCreatedText': 'Your account has been created and is waiting for administrator approval. You can log in once an administrator has approved your account.',
    'auth.errorCreatingUser': 'Error Creating User',
    'auth.enterEmail': 'Enter an email address.',
    'auth.userNotFoundReset': 'User not found. Check your email address.',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordDescription': 'Enter your email address to receive a password reset link.',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.sending': 'Sending...',
    'auth.stayLoggedIn': 'Stay logged in.',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.login': 'Login',
    'auth.loginToStart': 'Login to start tracking time',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enterYourEmail': 'Enter your email',
    'auth.enterYourPassword': 'Enter your password',
    'auth.resetEmailSent': 'Reset email sent',
    'auth.resetEmailSentText': 'A password reset link has been sent to {email}. Check your inbox.',
    'auth.resetEmailError': 'Could not send password reset email. The password-reset Edge Function may not be deployed. Please contact an administrator.',
    'auth.resetEmailSuccess': 'Password reset email has been sent! Check your inbox (and spam folder) for the reset link. The link is valid for 1 hour.',
    'auth.holdToShowPassword': 'Hold to show password',
    'auth.error': 'Error',
    'auth.unknownError': 'Unknown error',
    'auth.checkConsole': 'Check the browser console (F12) for more details.',
    'auth.loggedOut': 'Logged Out',
    'auth.loggedOutText': 'You have been successfully logged out.',
    'admin.existingUsers': 'Existing Users',
    
    // Weekly Entry Export
    'weekly.exportFailed': 'Export Failed',
    'weekly.noData': 'No Data',
    'weekly.noEntriesForWeek': 'No entries found for this week.',
    
    // Time Overview
    'overview.title': 'Project Overview',
    'overview.subtitle': 'Hours per project - {name} hours',
    'overview.allTime': 'All time',
    'overview.thisMonth': 'This month',
    'overview.thisWeek': 'This week',
    'overview.totalHours': 'Total Hours',
    'overview.projects': 'Projects',
    'overview.avgPerProject': 'Avg per Project',
    'overview.project': 'Project',
    'overview.entries': 'Entries',
    'overview.percentage': 'Percentage',
    'overview.visualization': 'Visualization',
    'overview.total': 'TOTAL',
    'overview.loading': 'Loading...',
    'overview.noHoursFound': 'No hours found for the selected period.',
    
    // Admin Panel Tabs
    'admin.tab.users': 'Users',
    'admin.tab.weeks': 'Weeks',
    'admin.tab.reminders': 'Reminders',
    'admin.tab.export': 'Export',
    'admin.tab.overtime': 'Overtime',
    'admin.tab.timebuzzer': 'Timebuzzer',
    
    // Overtime
    'overtime.title': 'Overtime Tracking',
    'overtime.description': 'View your overtime with percentage breakdown. A normal workday (Monday to Friday) is 8 hours.',
    'overtime.percentageRules': 'Percentage rules: After 8 hours on weekdays: 9th & 10th hour = 125%, every hour after 10 hours = 150%. Saturday = 150% (all hours). Sunday = 200% (all hours).',
    'overtime.period': 'Period',
    'overtime.week': 'Week',
    'overtime.month': 'Month',
    'overtime.year': 'Year',
    'overtime.all': 'All',
    'overtime.calculate': 'Calculate Overtime',
    'overtime.calculating': 'Calculating...',
    'overtime.totalOvertime': 'Total Overtime',
    'overtime.percentageBreakdown': 'Overtime per Percentage:',
    'overtime.hours125': '9th & 10th hour (weekdays)',
    'overtime.hours150': 'After 10th hour & Saturday',
    'overtime.hours200': 'Sunday',
    'overtime.perDayBreakdown': 'Overtime per Percentage:',
    'overtime.details': 'Details',
    'overtime.entries': 'entries',
    'overtime.project': 'Project',
    'overtime.workType': 'Work Type',
    'overtime.time': 'Time',
    'overtime.hours': 'Hours',
    'overtime.notes': 'Notes',
    'overtime.weekend': 'Weekend',
    'overtime.totalHours': 'h total (all hours are overtime)',
    'overtime.totalHoursNormal': 'h total - {normalHours}h normal',
    'overtime.clickToCalculate': 'Click on "Calculate Overtime" to calculate the overtime.',
    'overtime.overnightTitle': 'Overnight stays',
    'overtime.overnightCount': 'Total overnight stays',
    'overtime.overnightNone': 'No overnight stays in this period.',
    'overtime.missingInformation': 'Missing Information',
    'overtime.selectWeekAndYear': 'Please select a week and year.',
    'overtime.error': 'Error',
    'overtime.failedToCalculate': 'Failed to calculate overtime',
    'nav.overtime': 'Overtime',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.confirm': 'Confirm',
    'common.user': 'User',

    // Bug Report
    'View.manage': 'View and manage bug reports submitted by users',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Get language from localStorage or default to English
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('bampro_language');
      if (saved && ['nl', 'en'].includes(saved)) {
        return saved as Language;
      }
    }
    return 'en';
  });

  // Save language preference to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('bampro_language', lang);
    }
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || translations['en'][key] || key;
    
    // Replace parameters like {name} with actual values
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, String(params[param]));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};


