// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables so you can point the app at your own Supabase project
const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL || 'https://xnypbrdgskmdmpwanfnc.supabase.co';
const supabaseKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueXBicmRnc2ttZG1wd2FuZm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzEyODQsImV4cCI6MjA2NjM0NzI4NH0.K1sc99LqDRSY5BwTaBtKrZX1XXmf-_-EJlYczrS-8_E';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);